### ISSUE TITLE
Add-AzureRmAccount vs Login-AzureRmAccount

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#1]
Why use Login-AzureRmAccount in this course? The official command is Add-AzureRmAccount. 
Login-AzureRmAccount is just an Alias.

https://msdn.microsoft.com/en-us/library/mt619248.aspx
https://msdn.microsoft.com/en-us/library/mt619267.aspx
get-help login-azurermaccount

**Comment by polichtm** [comment]
Marcel,

 

Either one is obviously fully functional and acceptable. One might argue that the verb of Login-AzureRmAccount seems to more accurately reflect the underlying purpose, and from what I recall, that might have been the rationale for using it. In any case, this might be a chance to introduce the concept of aliases to students…

 

Rgds

Marcin
