### ISSUE TITLE
Module 4 - Availability Sets and managed disks

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#103]
Recently managed disks are introduced. When you create an availability set, managed disks are enabled by default. Following the instructions, it is not possible to add newly created vm to the availability set because VMs do not use managed disks by default.

If you enable managed disks while creating a new VM, you can add the VM to the avaibility set.

Another approach is that you disable managed disks when you create an availibility set.

In neither way, the scripts of the next exercise will not work and should be modified.

**Comment by polichtm** [comment]
The script should be running fine as long as you disable the managed disk option
