### ISSUE TITLE
Lab 3 PS Issue for VM creation

### ISSUE THREAD

**Issue by andrewbeldean** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#104]
Please change Line 43 of the script to 👍 
$storageAccount = (Get-AzureRmStorageAccount | Where-Object {($_.Location -eq $location) -and ($_.ResourceGroupName -eq $rgName) -and ($_.StorageAccountName -like $($rgName.ToLower() + "disks*"))})[0]
Thanks

**Comment by KarineMerritt** [comment]
You are missing an underscore in your 3rd line:
($_.ResourceGroupName etc.

**Comment by polichtm** [comment]
This is already correct in 20533-ImplementingMicrosoftAzureInfrastructureSolutions / Allfiles / Labfiles / Lab03 / Starter / CreateRmVM.ps1
