### ISSUE TITLE
Lab 7 Sales Database is not there?

### ISSUE THREAD

**Issue by andrewbeldean** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#105]
Opened up SQL MS on MIA-CL1 and logged on as student, however the sales database is not there?

Can't seem to find it either to attach it
In the Connect to Server dialog box, specify the following settings, and click Connect:
o Server type: Database Engine
o Server name: MIA-CL1
o Authentication: Windows Authentication
3. In SQL Server Management Studio, in Object Explorer, under the MIA-CL1 server, expand Databases
and verify that the sales database is listed.

**Comment by polichtm** [comment]
Make sure that you run Setup-Azure
