### ISSUE TITLE
Module 11 Demos and Labs have completely changed from Slides and GitHub Labs

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#106]
I have been struggling to do the Demos from the notes in the slide deck, but everything has changed. As I'm preparing this class and have never done the démos before, it's a bit of a challenge. 

So I decided to try the Labs first, as they are likely to be more up to date, but even they have changed. I've posted the updates.
Lab11, Ex1, task1, Line 3: On the menu hub, click New, and then click Monitoring + management
N.B. Monitoring + Management has gone.
Replace with: On the menu hub, click More services, Search for Automation, click Automation Accounts
Lab11, Ex1, task1, Line 4:  In the Monitoring + management blade, click Automation.
Replace with: Click Add
Lab11, Ex2, Task3, Line 3. In the Settings blade click Assets.
Replace with: In Resources click Assets

**Comment by KarineMerritt** [comment]
Update: Just on more update for the Lab procedures:
Lab11, Ex2, Task3, Line 3. In the Settings blade click Assets.
Replace with: In Resources click Assets

**Comment by polichtm** [comment]
Here you go:
          
Create an OMS workspace
1.	Ensure that you are signed in to MIA-CL1 as Student with the password Pa55w.rd, and that the setup script you ran in the previous demonstration to prepare the environment has completed.
2.	Sign in to the Azure portal by using the Microsoft account of the Service Administrator or a Co-Administrator of your Azure subscription.
3.	From the Azure portal, create an OMS workspace with the following settings:
o	OMS Workspace: A unique name in the portal.mms.microsoft.com namespace that can include 4 to 63 letters, digits, and dashes.
o	Subscription: Your Azure subscription
o	Resource group: Create a new resource group named 20533C1101-DemoRG
o	Location: An Azure region close to your location
o	Pricing tier: Free
4.	Wait until the workspace creation completes. This should take no more than a minute.


                    
Add solutions to OMS 
1.	From the blade of the newly created workspace, navigate to the OMS Portal.
2.	If prompted, sign in with the same account you used to authenticate to access your Azure subscription.
3.	From the OMS interface, browse to the Solutions Gallery, and then add the Activity Log Analytics solution and the Agent Health solution to the newly created workspace.



     
Install the Microsoft Monitoring Agent on an Azure VM

 
If the Session Expired dialog box appears while performing this demonstration, click Refresh, select the Don’t ask me again check box, then click SKIP THIS STEP AND CONTINUE.


1.	Click Settings on the home page of Microsoft Operations Management Suite.
2.	Click Connected Sources and ensure that the content of the Windows Servers page is displayed. Note the number of connected computers.
3.	Switch back to the Azure portal. On the Log Analytics blade of the newly created workspace, click Virtual machines, and then connect the myVM0 and myVM1 virtual machines to the workspace.
4.	Wait until the OMS Connection status of myVM0 and myVM1 changes to This workspace. This should take a few minutes. 
5.	Switch back to the Connected Sources page of the OMS interface.
6.	Refresh the Connected Sources page of the Microsoft Operations Management Suite interface, and then verify that the number of connected computers increased by two.


Review the search functionality
1.	Navigate to the Log Search page of the Microsoft Operations Management Suite interface.
2.	If prompted, step through the Search quick tips.
3.	Click Favorites. In the Saved Searches pane, click All Configuration Changes. 
 
Note that at this point, most likely the data collected from the client computer has not been indexed yet, so it will not be displayed in the results pane.


    
Configure log collection
•	From the Microsoft Operations Management Suite interface, navigate to the Settings page, click Data, click Windows Event Logs, and then verify that the collection of Windows System Event logs includes Error, Warning, and Informational events.

**Comment by polichtm** [comment]
btw. Monitoring + Management is still in the portal

**Comment by KarineMerritt** [comment]
Thanks for the procedure.
