### ISSUE TITLE
Setup-azure error

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#110]
Hi, When I run setup-azure, I get errors. I believe this is because I have two subscriptions. MSDN and Azure Pass. Should I do something before running the command?
N.B. This happens right from choice 1 in azure-setup.

**Comment by polichtm** [comment]
Karine
setup-azure will recognize that the account you are using to authenticate is associated with two subscriptions and will prompt you to select the one you want to use for the labs
What specifically are the errors you are referring to?
Btw. pls note that we just posted a new version of the course scripts - make sure you are using this version.
rgds
Marcin

**Comment by KarineMerritt** [comment]
Hi Marcin,
I have just downloaded the new version of the class from CWDL. Does it have the right version of the scripts, or is it already out of date?

Thanks
Karine

**Comment by polichtm** [comment]
Hi Karine,
The update took place today - so it depends on the timing. A quick way to verify this would be to look at the content of the Modules folder on your system and comparing it with the content of GitHub. If the number/names of modules matches, you have the updated version. If not, replace entire Allfiles with the content on GitHub
rgds
Marcin

**Comment by KarineMerritt** [comment]
Hi Marcin, 
I've imported the VM and looking on disk D:, that answers my question. There are no Allfiles anymore!
So I've downloaded the latest from GitHub and have tried again and I get the error that the setup-azure doesn't exist. I explicitly imported the set-azure module and it worked. 

Am I going to have to import every single module manually and also get all the students to do the same thing?
Regards
Karine

**Comment by polichtm** [comment]
Hi Karine,
The first part is intended. Allfiles are no longer included in the image but you need to download them from Github.
Regarding the second part, pls post the output of the following (from the Windows PowerShell prompt): 
$env:psmodulePath 
rgds
Marcin

**Comment by KarineMerritt** [comment]
C:\Users\Student\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\;C:\Program Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\;D:\Modules

Regards
Karine

**Comment by polichtm** [comment]
This looks fine. Do you have individual modules subdirectories in D:\Modules? If so, restart your computer and try again. 
rgds
Marcin

**Comment by KarineMerritt** [comment]
OK. Rebooted (Took ages because of Windows Update) and yes, it's fine. I ran reset-azure and it found it.

Should the set up guide be updated to include copying all these files to th D drive and rebooting?
Correcting the wrong Admin password and running the import script as administrator could be done at the same time.

Thanks for your help
Regards
Karine

**Comment by polichtm** [comment]
I'll look into the setup guide - what do you mean by "the wrong Admin password"> 
You should ont have to import modules - as long as they are in the correct location (i.e. D:\Modules)
rgds
Marcin

**Comment by KarineMerritt** [comment]
There are two errors in the setup guide. 
The Admin password is given as Pa$$w0rd, when it is in fact Pa55w.rd 
and right click ImportVMs.ps1, run in PowerShell, when this won't work as you need to run as Administrator.
Rgds
Karine

**Comment by polichtm** [comment]
Karine,
I don't see ImportVMs.ps1 being referenced in the setup guide. Can you clarify where exactly are you seeing this?
rgds
Marcin

**Comment by KarineMerritt** [comment]
Here it is:
8. Import the Virtual Machines on the Instructor Computer
1. Browse to D:\Program Files\Microsoft Learning\20533\Drives\.
2. Right-click D:\Program Files\Microsoft Learning\20533\Drives\20533C_ImportVirtualMachines.ps1, and then click Run with PowerShell. Press Y, and then press Enter if prompted.
3. At the On which disk drive are the course virtual machines extracted prompt, type the appropriate drive letter to which the course images are extracted, and then press Enter

**Comment by polichtm** [comment]
This has been addressed - the updated setup guide will be available shortly
rgds
Marcin

**Comment by KarineMerritt** [comment]
Great reactivity. I wish all classes were like this one!
Thanks
Karine

**Comment by polichtm** [comment]
appreciate the compliment - hope you'll enjoy the class
rgds
Marcin

**Comment by molenaar** [comment]
Why didn't you create a new branche for the new version instead of completely replace the current version. Officially the updated version is to be released at the end of march. This week I have a class based on the current version. We will use the updated instructions, however it would be nice to have a fallback scenario.

Also notice that the lab-hosters need time to update their lab environements.

So why not create different branches like the 20532 repository?

**Comment by polichtm** [comment]
Primarily because I wasn't planning on maintaining the second branch. If there is a need to retrieve the earlier version of the content, then this can be accomplished by cloning the tree e3fe00343c (corresponding to the commit e3fe003). I could potentially fork the master and reset it back to that commit if you have any issues with the approach I'm describing. Feel free to let me know.
thnx
Marcin

**Comment by molenaar** [comment]
For teachers it is not about maintaining multiple branches. Labs have to be up to date.
It is more about having options to choose between different version when you have to deliver a class. This is a grace period moving from the current to the next update. Some teachers have time to prepare the coming weeks. Others have to deliver the current version right now without having time to rework the whole course after a weekend update.

You could create a second branche with a more readable label until the final release at the end of this month. I point my student directly to github pages without generating word document. Perhaps I should have doen that.... Pointing to a specific tree/commit isn't that user friendly.  When the updated c version is released you could remove the old branche/label/whatever you call  it, or swap/merge, so teachers did have enough time to prepare,
compare the differences and make the change. After the end of march everyone should use the updated version, both students and teachers, so it will not be a problem anymore.

For me is cloning an older tree/commit not that of a problem, however I am not sure that other teachers are that familiar with git.

Thanks
Marcel

_____________________________

**Comment by polichtm** [comment]
As requested, I created a separate branch labeled Labs-for-MOC-20533-Pre-March-2017
thnx
Marcin
