### ISSUE TITLE
New Storage account for DSC

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#113]
In module 4 a storage account is needed to store the DSC script. 
I would suggest to modify the script and create a new storage account in the right resource group instead of trying to retrieve an existing storage account from the previous account.
Now Microsoft is moving to managed disks so eventually Availability Sets and Virtual Machine are all based on managed disk. So changing all the instructions to disable managed disks isn't the solution. Try to make the scripts work for all scenario's: without or without managed disks and diagnostics.

**Comment by polichtm** [comment]
Appreciate the feedback - unfortunately with Azure we deal with the constantly moving target. 
We will certainly account for any changes that will affect the functionality of the scripts/lab instructions.
