### ISSUE TITLE
Lab 11 Setup azure Domain Name Label error

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#117]
According to this issue: https://github.com/deis/deis/issues/4854 an error might occur when you run setup-azure for module 11. 
The azuredeploy.json file (https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/blob/master/Allfiles/Labfiles/Lab11/Starter/Templates/azuredeploy.json) creates a uniquestring at   "dnsNameforLBIP": "[uniqueString(resourceGroup().id)]"
However the domain name label must conform the following expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$. , so the script fails when the uniquestring begin with a number.

**Comment by polichtm** [comment]
added a character string to the beginning of the dnsNameforLBIP
