### ISSUE TITLE
New manual from the 17th of March is already out of date

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#118]
In module 2, there is a paragraph on VNet peering, as the information was rather vague, I read the Technet articles and decided to test it out. But this doesn't exist anymore in the Azure portal. There is a  connections link, but this doesn't seem to be a replacement.

**Comment by polichtm** [comment]
VNet peering is very much alive and is not likely to go away any time soon. Pls see attached screenshot
![vnetpeeringg](https://cloud.githubusercontent.com/assets/10284906/24402807/2675972a-1388-11e7-95ce-e739fa8eb60b.png)

**Comment by polichtm** [comment]
As far as manual being "out of date", that's the nature of Azure and the direct result of its quite remarkable pace of changes. We'll be applying updates as frequently as possible to account for this.

**Comment by KarineMerritt** [comment]
Thanks for the screen shot. I was in the wrong blade.
It's all slowly falling into place. 
Regards Karine

**Comment by polichtm** [comment]
you're welcome
