### ISSUE TITLE
Lab3 Failures

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#119]
New-AzureRm20533C03VM.ps1 fails because it trys to create VM in wrong subscription.

Regards
Karine

**Comment by KarineMerritt** [comment]
I've just run it again and it did ask!

**Comment by polichtm** [comment]
Karine,
the error messages seem to indicate that you don't have a storage account in the resource group 20533C0301-LabRG. This might be the result of one of two issues:
- you skipped task 1 of exercise 1 (or you missed one of the steps when performing it)
- you chose the option to use managed disks in task 1 of exercise 1
Pls let me know if this is the case
thnx
Marcin

**Comment by KarineMerritt** [comment]
Hi Marcin,

I did task 1. I couldn't find any information about whether the disks are managed disks in the parameters, so I created another VM with Non-managed disks and the only difference visible after creation is the size doesn't show for the disk of the new machine. The script was OK after this.

Thanks for you help.

**Comment by KarineMerritt** [comment]
The JSON deployment fails too:
ResDevApp1' failed with message '{
11:25:20 -   "error": {
11:25:20 -     "code": "InvalidParameter",
11:25:20 -     "target": "vmSize",
11:25:20 -     "message": "The requested VM size Standard_D1 is not available in the current region. The 
11:25:20 - sizes available in the current region are: Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standar
11:25:20 - d_A5,Standard_A4,Standard_A6,Standard_A7,Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_D1_
11:25:20 - v2,Standard_D2_v2,Standard_D3_v2,Standard_D4_v2,Standard_D5_v2,Standard_D11_v2,Standard_D12_v2,Sta
11:25:20 - ndard_D13_v2,Standard_D14_v2,Standard_D15_v2,Standard_D2_v2_Promo,Standard_D3_v2_Promo,Standard_D4
11:25:20 - _v2_Promo,Standard_D5_v2_Promo,Standard_D11_v2_Promo,Standard_D12_v2_Promo,Standard_D13_v2_Promo,S
11:25:20 - tandard_D14_v2_Promo,Standard_F1,Standard_F2,Standard_F4,Standard_F8,Standard_F16,Standard_DS1_v2,
11:25:20 - Standard_DS2_v2,Standard_DS3_v2,Standard_DS4_v2,Standard_DS5_v2,Standard_DS11_v2,Standard_DS12_v2,
11:25:20 - Standard_DS13_v2,Standard_DS14_v2,Standard_DS15_v2,Standard_DS2_v2_Promo,Standard_DS3_v2_Promo,Sta
11:25:20 - ndard_DS4_v2_Promo,Standard_DS5_v2_Promo,Standard_DS11_v2_Promo,Standard_DS12_v2_Promo,Standard_DS
11:25:20 - 13_v2_Promo,Standard_DS14_v2_Promo,Standard_F1s,Standard_F2s,Standard_F4s,Standard_F8s,Standard_F1
11:25:20 - 6s,Standard_A1_v2,Standard_A2m_v2,Standard_A2_v2,Standard_A4m_v2,Standard_A4_v2,Standard_A8m_v2,St
11:25:20 - andard_A8_v2. Find out more on the available VM sizes in each region at 
11:25:20 - https://aka.ms/azure-regions."

I am not looking forward to giving this class. I will be in a different region and I have no idea what will bug and what won't.

**Comment by KarineMerritt** [comment]
Small error in Lab 3 text: Open Powershell, then all further references are for ISE.
1. On MIA-CL1, right-click the Windows PowerShell icon on the taskbar and click **Run as Administrator**. When prompted by User Account Control, click **Yes**.
2. In the Windows PowerShell ISE window, at the console prompt, type the following cmdlet, and then press Enter:
etc.

**Comment by KarineMerritt** [comment]
ResDevWindowsDeploy.ps1 fails too. Same reason. VM size not available in this region

**Comment by polichtm** [comment]
Karine,
This has been resolved - I changed the VM size to Standard_D1_v2
