### ISSUE TITLE
Setup-Azure for Lab 10 fails

### ISSUE THREAD

**Issue by Rokory** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#120]
Here is the error, I get:

New-AzureRmResourceGroupDeployment : 21:22:09 - Resource 
Microsoft.Compute/virtualMachines/extensions 'adVM/CreateADForest' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'CreateADForest'. Error 
message: \"The DSC Extension received an incorrect input: Compilation errors occurred while 
processing configuration 'CreateADPDC'. Please review the errors reported in error stream and 
modify your configuration code appropriately. Exception calling \"Substring\" with \"2\" 
argument(s): \"Index and length must refer to a location within the string.\r\nParameter name: 
length\"\n\nAnother common error is to specify parameters of type PSCredential without an 
explicit type. Please be sure to use a typed parameter in DSC Configuration, for example:\n\n   
 configuration Example {\n        param([PSCredential] $UserAccount)\n        ...\n    
}.\nPlease correct the input and retry executing the extension.\"."
      }
    ]
  }
}'
In D:\Labfiles\Lab10\Starter\Setup-20533C10Lab.ps1:91 Zeichen:1
+ New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.N 
   ewAzureResourceGroupDeploymentCmdlet
 
New-AzureRmResourceGroupDeployment : 21:22:09 - VM has reported a failure when processing 
extension 'CreateADForest'. Error message: "The DSC Extension received an incorrect input: 
Compilation errors occurred while processing configuration 'CreateADPDC'. Please review the 
errors reported in error stream and modify your configuration code appropriately. Exception 
calling "Substring" with "2" argument(s): "Index and length must refer to a location within the 
string.
Parameter name: length"
Another common error is to specify parameters of type PSCredential without an explicit type. 
Please be sure to use a typed parameter in DSC Configuration, for example:
    configuration Example {
        param([PSCredential] $UserAccount)
        ...
    }.
Please correct the input and retry executing the extension.".
In D:\Labfiles\Lab10\Starter\Setup-20533C10Lab.ps1:91 Zeichen:1
+ New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.N 
   ewAzureResourceGroupDeploymentCmdlet

**Comment by polichtm** [comment]
The script and folder structure has been updated - pls make sure you use the latest content under Labfiles/Lab10/Starter
