### ISSUE TITLE
20533C_LAB_AK_04.md

### ISSUE THREAD

**Issue by kasunsjc** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#121]
I try to commit this but I dont have permissions for that

Following steps should be added to the file  20533C_LAB_AK_04.md when creating load balance back end pool configuration 

4. On the **Add backend pool** blade, in the **Name** text box, type **ResDevWebLBPool**, select **IPv4**, and then click **Associated to** drop down select **Availability set**.

5. On the **Availability set** drop down select **ResDevWebAS**.

6. On the **Target network IP configurations** click **Add a target network IP configurations**, on the **Target virtual machine** select **ResDevWebVM1** , on the **Network IP configuration** select **ipconfig1(x.x.x.x)**.

7. On the **Target network IP configurations** click **Add a target network IP configurations**, on the **Target virtual machine** select **ResDevWebVM2** , on the **Network IP configuration** select **ipconfig1(x.x.x.x)**

**Comment by polichtm** [comment]
You could submit a pull request. 
In any case, I updated the lab instructions
