### ISSUE TITLE
Lab 10 VM is not a DC

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#123]
During the setup-azure, it gives an error, the VM that is created doesnt become a DC.

Which lab do you want to set up? Type a number from 1 - 11:   10

The lab you want to set up is: Lab 10

Lab 10. Managing an Active Directory Hybrid Environment. Setup will deploy a Windows Server 2016 Azure VM hosting a do
main controller and then remove any cached Azure subscription details from the current Windows PowerShell session.
Is this is correct? Y/N?:   Y
The lab to set up is: Lab 10
Transcript started, output file is D:\Logs\Setup-Azure-10.log

Now setting up Lab 10
Using the subscription:  Azure Pass  Id:  0821a289-fd18-4fa0-9d5f-437db768c7d0  (Resource Manager)

Environment           : AzureCloud
Account               : wkh20533c270317@outlook.com
TenantId              : 725f0118-8be3-4cc4-b10d-57c32aa7a67a
SubscriptionId        : 0821a289-fd18-4fa0-9d5f-437db768c7d0
SubscriptionName      : Azure Pass
CurrentStorageAccount : 

Key   : Canada East
Value : 1
Name  : Canada East

Key   : East US
Value : 2
Name  : East US

Key   : Canada Central
Value : 3
Name  : Canada Central

Key   : Korea South
Value : 4
Name  : Korea South

Key   : Japan East
Value : 5
Name  : Japan East

Key   : East US 2
Value : 6
Name  : East US 2

Key   : South Central US
Value : 7
Name  : South Central US

Key   : UK South
Value : 8
Name  : UK South

Key   : Australia East
Value : 9
Name  : Australia East

Key   : UK West
Value : 10
Name  : UK West

Key   : Brazil South
Value : 11
Name  : Brazil South

Key   : West Europe
Value : 12
Name  : West Europe

Key   : Australia Southeast
Value : 13
Name  : Australia Southeast

Key   : West US 2
Value : 14
Name  : West US 2

Key   : Central US
Value : 15
Name  : Central US

Key   : Korea Central
Value : 16
Name  : Korea Central

Key   : North Central US
Value : 17
Name  : North Central US

Key   : North Europe
Value : 18
Name  : North Europe

Key   : West US
Value : 19
Name  : West US

Key   : East Asia
Value : 20
Name  : East Asia

Key   : West Central US
Value : 21
Name  : West Central US

Key   : Japan West
Value : 22
Name  : Japan West

Key   : Southeast Asia
Value : 23
Name  : Southeast Asia

Enter the number (value) of the Azure region to use: 23
Your Azure region is:  Southeast Asia
VERBOSE: Performing the operation "Replacing resource group ..." on target "".
VERBOSE: 8:10:11 PM - Created resource group '20533C1001-LabRG' in location 'southeastasia'

ResourceGroupName : 20533C1001-LabRG
Location          : southeastasia
ProvisioningState : Succeeded
Tags              : 
TagsTable         : 
ResourceId        : /subscriptions/0821a289-fd18-4fa0-9d5f-437db768c7d0/resourceGroups/20533C1001-LabRG

VERBOSE: Performing the operation "Creating Deployment" on target "20533C1001-LabRG".
VERBOSE: 8:10:19 PM - Template is valid.
VERBOSE: 8:10:25 PM - Create template deployment 'azuredeploy-0331-0310'
VERBOSE: 8:10:25 PM - Checking deployment status in 5 seconds
VERBOSE: 8:10:33 PM - Resource Microsoft.Resources/deployments 'VNet' provisioning status is running
VERBOSE: 8:10:33 PM - Resource Microsoft.Network/virtualNetworks 'adVNET' provisioning status is succeeded
VERBOSE: 8:10:34 PM - Checking deployment status in 5 seconds
VERBOSE: 8:10:42 PM - Resource Microsoft.Storage/storageAccounts 'ifwed3hzkj2ssadsa' provisioning status is succeeded
VERBOSE: 8:10:42 PM - Resource Microsoft.Network/networkInterfaces 'adNic' provisioning status is succeeded
VERBOSE: 8:10:42 PM - Resource Microsoft.Network/loadBalancers 'adLoadBalancer' provisioning status is succeeded
VERBOSE: 8:10:42 PM - Resource Microsoft.Network/publicIPAddresses 'adPublicIP' provisioning status is succeeded
VERBOSE: 8:10:42 PM - Resource Microsoft.Compute/availabilitySets 'adAvailabiltySet' provisioning status is succeeded
VERBOSE: 8:10:42 PM - Resource Microsoft.Resources/deployments 'VNet' provisioning status is succeeded
VERBOSE: 8:10:43 PM - Checking deployment status in 5 seconds
VERBOSE: 8:10:51 PM - Resource Microsoft.Compute/virtualMachines 'adVM' provisioning status is running
VERBOSE: 8:10:52 PM - Checking deployment status in 5 seconds
New-AzureRmResourceGroupDeployment : 8:11:00 PM - Resource Microsoft.Compute/virtualMachines 'adVM' failed with 
message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'CreateADForest'. Error message: \"The DSC 
Extension received an incorrect input: Compilation errors occurred while processing configuration 'CreateADPDC'. 
Please review the errors reported in error stream and modify your configuration code appropriately. Exception 
calling \"Substring\" with \"2\" argument(s): \"Index and length must refer to a location within the 
string.\r\nParameter name: length\"\n\nAnother common error is to specify parameters of type PSCredential without an 
explicit type. Please be sure to use a typed parameter in DSC Configuration, for example:\n\n    configuration 
Example {\n        param([PSCredential] $UserAccount)\n        ...\n    }.\nPlease correct the input and retry 
executing the extension.\"."
      }
    ]
  }
}'
At D:\Labfiles\Lab10\Starter\Setup-20533C10Lab.ps1:91 char:1
+ New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupD 
   eploymentCmdlet
 
New-AzureRmResourceGroupDeployment : 8:11:00 PM - VM has reported a failure when processing extension 
'CreateADForest'. Error message: "The DSC Extension received an incorrect input: Compilation errors occurred while 
processing configuration 'CreateADPDC'. Please review the errors reported in error stream and modify your 
configuration code appropriately. Exception calling "Substring" with "2" argument(s): "Index and length must refer 
to a location within the string.
Parameter name: length"
Another common error is to specify parameters of type PSCredential without an explicit type. Please be sure to use a 
typed parameter in DSC Configuration, for example:
    configuration Example {
        param([PSCredential] $UserAccount)
        ...
    }.
Please correct the input and retry executing the extension.".
At D:\Labfiles\Lab10\Starter\Setup-20533C10Lab.ps1:91 char:1
+ New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupD 
   eploymentCmdlet
 
New-AzureRmResourceGroupDeployment : 8:11:00 PM - Template output evaluation skipped: at least one resource 
deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for 
usage details.
At D:\Labfiles\Lab10\Starter\Setup-20533C10Lab.ps1:91 char:1
+ New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupD 
   eploymentCmdlet
 
New-AzureRmResourceGroupDeployment : 8:11:00 PM - Template output evaluation skipped: at least one resource 
deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for 
usage details.
At D:\Labfiles\Lab10\Starter\Setup-20533C10Lab.ps1:91 char:1
+ New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupD 
   eploymentCmdlet
 

DeploymentName          : azuredeploy-0331-0310
CorrelationId           : cf1e594e-6944-4bdf-8c73-3590cf6a1dce
ResourceGroupName       : 20533C1001-LabRG
ProvisioningState       : Failed
Timestamp               : 3/31/2017 3:10:57 AM
Mode                    : Incremental
TemplateLink            : 
TemplateLinkString      : 
DeploymentDebugLogLevel : 
Parameters              : {[adminUsername, 
                          Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], 
                          [adminPassword, 
                          Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], 
                          [domainName, 
                          Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], 
                          [windowsserver, 
                          Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable]...}
ParametersString        : 
                          Name             Type                       Value     
                          ===============  =========================  ==========
                          adminUsername    String                     Student   
                          adminPassword    String                     Pa55w.rd1234
                          domainName       String                     adatum.com
                          windowsserver    String                     2016-Datacenter
                          _artifactsLocation  String                     https://raw.githubusercontent.com/Azure/azur
                          e-quickstart-templates/master/active-directory-new-domain
                          _artifactsLocationSasToken  SecureString                         
                          
Outputs                 : 
OutputsString           : 

Removing cached Azure subscription references...
Removing local Azure subscription certificates...
Signing out of Azure...

Lab 10 setup is complete
Started at 3/30/2017 8:09:17 PM
Ended at 3/30/2017 8:11:02 PM
 
Total elapsed time is 1 minutes
 
Transcript stopped, output file is D:\Logs\Setup-Azure-10.log

**Comment by polichtm** [comment]
I tested this yesterday (successfully). Pls make sure that you have the most recent (and complete) set of Labfiles on your lab VM
