### ISSUE TITLE
Lab4 instruction error in 20533_LAB_04.md

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#124]
Managed YES /NO needs to be consistent. If mixed, lab fails.

HA

#### Task 1: Create virtual machines in an availability set

- Managed: **Yes** - in availability set

but in the VM creating Use managed disk setting the option were to use No,
in order for Availablity set to work will need to have the same Managed disk settings

ResDevWebLBIP

**Comment by polichtm** [comment]
resolved
