### ISSUE TITLE
Module 3 lab error

### ISSUE THREAD

**Issue by derricksobrien** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#129]
Several students had difficulty with the Lab for Module 3

The Powershell script can fail depending on the VM size offered in the region.  The password may need to be modified in the supplied script

See also..
scripts in Labs for Module 3 and 4. Specifically the script CreateRmVM.ps1 in Mod. 3 lab A Ex. 1 and the DeployAzureDSC.ps1 script in Mod. 4 Lab Ex. 2 fail with a "Cannot convert "System.Object[]' to the type 'System.String' and other errors

If this is the storage account issue, as in relative uri issue: there is a solution, use the [0] for the storage account uri. The issue is since introducing an additional storage account for diagnostics when creating a VM, you now have more than one stoarage account in Azure, however the script works as is, on the premise you only have one.

So force the script to select the right storage account. I use an index selector on the end: [0] as the quickest solution.

Mark Baugher
Sr. Microsoft Instructor

**Comment by chrzanowskiItta** [comment]
ok Did you update the Lab instructions on GitHub ?

**Comment by polichtm** [comment]
Mark - diagnostics should be disabled in both Module 3 and Module 4 when creating the VM via the Azure portal. To address potential confusion, we'll look into building more resiliency into the scripts.
