### ISSUE TITLE
Module 2

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#130]
Hello
13.	At the Windows PowerShell command prompt, type the following command, and then press Enter:
Set-AzureVNetConfig -ConfigurationPath D:\Configfiles\Lab02\NetworkConfig.xml

When I run this command I have en a error ;
Set-AzureVNetConfig : BadRequest : **Cannot delete or modify subnet while in use 'GatewaySubnet'.**
At line:1 char:1
+ Set-AzureVNetConfig -ConfigurationPath D:\Labfiles\Lab02\Solution\Net ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureVNetConfig], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.SetAzureVNetConfigCommand

**Comment by polichtm** [comment]
Pls post the content of the NetworkConfig.xml you are using 
thnx
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response and not being able to reproduce the issue

**Comment by renaudwangler** [comment]
This is the error some students had this morning and this is why I suggest the stundent verifies the proper content of his xml reagrding his network config ;)

**Comment by polichtm** [comment]
appreciate the input...
rgds
Marcin
