### ISSUE TITLE
Convention folder...

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#131]
Hello, Just for my information and the students
I never really understand what do you mean by **D:03** !!!!!????
For me in the bellow example I whent in D:\Labfiles\Lab03\Starter
Is it correct ? tks

**_2.	In the Windows PowerShell Integrated Scripting Environment (ISE) window, open the New-AzureRm20533C03VM.ps1 script at **D:03**_**

**Comment by polichtm** [comment]
Where specifically are you seeing this?
thnx
Marcin

**Comment by chrzanowskiItta** [comment]
Hello in the LAB AK..

**Comment by polichtm** [comment]
Hello - where? Pls refer to the image
![image](https://cloud.githubusercontent.com/assets/10284906/24771038/62734b38-1b0c-11e7-8341-93ecd774c29f.png)

**Comment by chrzanowskiItta** [comment]
Here : for ex in lab 5
Exercise 2: Deploying a web app
▶	Task 1: Obtain a publishing profile
1.	In the Azure portal, on the blade of the web app that you created in the exercise 1, click Overview and then click Get publish profile. You might need to first click ... More if the Get publish profile option does not appear in the toolbar at the top of the blade.
2.	When prompted whether to open or save the .PublishSettings file, click Save. Internet Explorer will save the publishing profile in the Downloads folder on your lab computer.
3.	On the taskbar, click Visual Studio 2015.
4.	On the File menu, click Open, and then click Project/Solution.
5.	**_Browse to the folder **D:05*, click AdatumWebsite.sln, and then click Open._**

**Comment by polichtm** [comment]
Pls specify the file name and the line number on Github that you are referring to. The text you are referring to does not exist in LAK for module 3.
