### ISSUE TITLE
Demonstation instructions are not evolving

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#132]
Unlike Lab instructions that are continually updated, the Demo Instructions are cast in stone.
One of the Module 4 demos uses managed disks, when it shouldn't, making the following demo fail. But no update will be available in Github. 
Module 5 Demonstration: Deploying web apps by using Web Deploy Requires a new WebApp called **WebAppStandardPlan**, which is not available.

I'm not looking for a solution to this name not being available, but in general, I propose a démos folder where we can store and update the instructions once and share them in the way lab instructions are.

**Comment by polichtm** [comment]
We'll investigate the possibility of updating demos - in the meantime, pls use the App Service Plan that is available (btw. this is not a Web app but a service plan)
thnx
Marcin
