### ISSUE TITLE
Module 4 DSC

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#133]
When I run the script ps1 for DSC I have this error
et-AzureRmStorageAccountKey : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Name'. 
Specified method is not supported.

Help

**Comment by polichtm** [comment]
make sure that you DISABLE diagnostics when creating the VM in this lab/demo
rgds
Marcin

**Comment by chrzanowskiItta** [comment]
I  did..  I saw last week a post telling that we have to select name [] or
something like that....

**Comment by polichtm** [comment]
At this point, you should simply follow the directions as posted in the instructions
thnx
Marcin

**Comment by polichtm** [comment]
instructions have been updated - closing the issue
