### ISSUE TITLE
Module 4 add VHD

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#134]
hello bellow I dont have the option of selecting the **RG 20533C0401-LabRG**   like if this option is not displaying !!

•	Size: 1023
•	Storage Container: Select the existing storage account and the vhds container
6.	Wait for the operation to complete.
7.	Back on the ResDevWebVM1 - Disks blade, ensure that the HOST CACHING column contains the None entry and then click Save.
8.	Click + Add data disk.
9.	On the Attach unmanaged blade, specify the following settings and then click OK:
•	Name: ResDevWebVM1dd02
•	**_Resource group: ensure that the Use existing option is selected and click 20533C0401-LabRG in the drop down list._**

**Comment by derricksobrien** [comment]
We noticed that the Powershell script has different Resource group listed from the instructions.  Our students were able to run the script by changing the name of the Resource Group in the script.

The inconsistence should be addressed in these instructions

**Comment by polichtm** [comment]
Pls clarify what PowerShell script you are referring to and what is the Resource Group name that you used
thnx
Marcin

**Comment by polichtm** [comment]
The resource group 20533C0401-LabRG is not created by a script. You are supposed to create it manually in step 6 of task 1 of exercise 1. Similarly, ResDevWebVM1 is not created by any script but manually by following steps of task 1 of exercise 1. Pls make sure to review these instructions and follow them step by step.
