### ISSUE TITLE
Module 10 setup-azure not working

### ISSUE THREAD

**Issue by BaMi83** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#136]
When setting up Module 10 the whole class gets the following errors (see screenshot)
![2017-04-06 20_14_47-virsoft lab menu - global knowledge lab environment - internet explorer](https://cloud.githubusercontent.com/assets/26976733/24769169/c017263a-1b05-11e7-9bf5-5a0f7c88f2b2.png)

**Comment by polichtm** [comment]
Pls make sure that you are using the latest version of Allfiles. This issue has already been corrected
thnx
Marcin
