### ISSUE TITLE
Demofiles Module 6 uploadblobs.ps1 fails

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#137]
PS C:\Windows\system32> D:\Demofiles\Mod06\UploadBlobs.ps1
Get-AzureStorageKey : No default subscription has been designated. Use Select-AzureSubscription -Default <subscriptionName> to set 
the default subscription.
At D:\Demofiles\Mod06\UploadBlobs.ps1:11 char:23
+ ... countKey = (Get-AzureStorageKey -StorageAccountName $storageAccountNa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureStorageKey], ApplicationException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.StorageServices.GetAzureStorageKeyCommand
 
New-AzureStorageContext : Cannot validate argument on parameter 'StorageAccountKey'. The argument is null or empty. Provide an 
argument that is not null or empty, and then try the command again.
At D:\Demofiles\Mod06\UploadBlobs.ps1:12 char:99
+ ... AccountName $storageAccountName -StorageAccountKey $storageAccountKey
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureStorageContext], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorage 
   Context
 
Set-AzureStorageBlobContent : Could not get the storage context.  Please pass in a storage context or set the current storage 
context.
At D:\Demofiles\Mod06\UploadBlobs.ps1:19 char:3
+   Set-AzureStorageBlobContent -File $filename -Container $containerNa ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand
 
Set-AzureStorageBlobContent : Could not get the storage context.  Please pass in a storage context or set the current storage 
context.
At D:\Demofiles\Mod06\UploadBlobs.ps1:19 char:3
+   Set-AzureStorageBlobContent -File $filename -Container $containerNa ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand
 
Set-AzureStorageBlobContent : Could not get the storage context.  Please pass in a storage context or set the current storage 
context.
At D:\Demofiles\Mod06\UploadBlobs.ps1:19 char:3
+   Set-AzureStorageBlobContent -File $filename -Container $containerNa ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand

Running: Select-AzureSubscription -Default "MSDN Platforms" Fails too
 

PS C:\Windows\system32>

**Comment by polichtm** [comment]
I assume that this is also resolved after you reset the VM and downloaded the current version of Allfiles - correct?

**Comment by KarineMerritt** [comment]
No. This didn't work. I skipped this part of demo and continued.
