### ISSUE TITLE
I don't understand "Demonstration: Implementing Azure SQL Database" instruction

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#138]
Table and 100 rows inserted. OK
Script the dbo.demotable table as SELECT to the new Query Editor window, and then execute the resulting Transact SQL code.

**Comment by polichtm** [comment]
refer to the following screenshot:
![image](https://cloud.githubusercontent.com/assets/10284906/24841578/a658be0a-1d55-11e7-950a-be2984051f48.png)
