### ISSUE TITLE
SQL Database security demo

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#139]
These instructions are too vague and the labs don't contain the same tests.
In SQL Server Management Studio, view the server logins and verify that the DemoLogin login is listed. -Where?
Try connecting to the master database of the same logical SQL server by using the DemoLogin login with the password Pa55w.rd - How?
Try connecting to the demodb database of the same logical SQL server by using the DemoLogin login with the password Pa55w.rd - How?

**Comment by polichtm** [comment]
The demos are intentionally not providing step by step instructions in order to avoid discrepancies due to interface changes (since we cannot update demos the same way we update labs). It is expected that instructors have sufficient level of knowledge to perform basic management tasks in the technology area that they teach. If this is not the case, then I'd suggest to refer to the corresponding documentation online - starting with https://docs.microsoft.com/en-us/azure/sql-database/

**Comment by KarineMerritt** [comment]
OK. Understood. You're not interested. 
I won't post anymore comments.

**Comment by polichtm** [comment]
Karine,
we are interested in all constructive comments that will allow us to make this course better. However, as you know, currently we don't have the way to update demo steps - which is the very reason we make them less detailed. Based on your comments, we might consider including demos in the GitHub hosted content.

**Comment by renaudwangler** [comment]
Hi
 
I second the suggestion : Teaching these courses make us touch to a lot of things (and I assume not being an expert on all)... Having step by step demos would allow any trainer to, at least, show the expected content to the students...
 
Greetings from France :)
 
Renaud WANGLER
Formateur
Ib - groupe CEGOS
Tél. : +33 6 83 00 77 14

-------------------Informations légales------------------- 
Ce message et toutes les pièces jointes sont confidentiels et établis à l'attention exclusive de ses destinataires. 
Le présent mail ainsi que toutes les informations qu'il contient ne peuvent être considérés comme un engagement de quelque nature que ce soit de la part d'ib - groupe Cegos, tout accord devant être formulé par écrit. 
Le message reste la propriété exclusive d' ib - groupe Cegos. 
Toute utilisation ou diffusion non autorisée est interdite. 
ib - groupe Cegos décline toute responsabilité au titre de ce message s'il a été altéré, déformé ou falsifié.

________________________________

**Comment by polichtm** [comment]
Renaud, Karine,
appreciate the feedback and we will take this into consideration when designing the next revision of the course (that would require including Demos in the GitHub-hosted content). Let me know if I can assist in the meantime with any questions regarding the existing content that you might have. However, also pls keep in mind that this is not the intended platform for learning about Azure - especially considering that the questions raised above can be easily answered by reviewing online documentation at https://docs.microsoft.com/en-us/azure/sql-database/ 
rgds
Marcin

**Comment by renaudwangler** [comment]
Hi Marcin
 
To be honest, I'm currently teaching a course and did not entirely read the exchange you had with Karine...
My mail was about the "idea" of having consistants demos in the git hub ;)
 
Anyway : many thanks for the nice work you're doing !
 
Greetings
 
Renaud WANGLER
Formateur
Ib - groupe CEGOS
Tél. : +33 6 83 00 77 14

-------------------Informations légales------------------- 
Ce message et toutes les pièces jointes sont confidentiels et établis à l'attention exclusive de ses destinataires. 
Le présent mail ainsi que toutes les informations qu'il contient ne peuvent être considérés comme un engagement de quelque nature que ce soit de la part d'ib - groupe Cegos, tout accord devant être formulé par écrit. 
Le message reste la propriété exclusive d' ib - groupe Cegos. 
Toute utilisation ou diffusion non autorisée est interdite. 
ib - groupe Cegos décline toute responsabilité au titre de ce message s'il a été altéré, déformé ou falsifié.

________________________________

**Comment by polichtm** [comment]
Hi Renaud,
appreciated
rgds
Marcin
