### ISSUE TITLE
SQL Database auditing demo doesn't resemble the Azure portal any more

### ISSUE THREAD

**Issue by KarineMerritt** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#140]
Configure SQL Database auditing In the Azure portal, navigate to the demodb blade.  
From the demodb blade, navigate to the Auditing & Threat detection blade. 
None of the following applys:
On the Auditing & Threat detection blade, clear the Inherit settings from server check box, and then apply the following settings: Auditing: ON Auditing Type: Table
**Auditing is now blob and no server settings are displayed.**

_Are we still not going to update and correct Demos in the same way as Labs?_

**Comment by polichtm** [comment]
Pls provide the screenshot of what you are referring to - this DOES NOT match what I'm seeing in the portal.

Btw. this is precisely the challenge we are trying to avoid by making demos as generic as possible - which incidentally you are apparently unhappy about according to the issue 139 that you raised (SQL Database security demo #139). Regretfully we do not have a way to update demos steps at this point, so you'll need to be proactive and ensure that you step through each demo prior to teaching the course and account for any changes to the Azure portal interface.
