### ISSUE TITLE
file path problem

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#144]
Hello.
On each exercise, after exporting the document in Word format via the included powershell (and the recommended version of tools) each string including path (ex: "D:\Labfiles\Mod01\starter") is strangley shortened (here "D:01") in the resultant word document (probably due to the "\" character in the string and/or to the french locale I'm using on my export computer).

Any help welcome ;)

**Comment by polichtm** [comment]
Hello, 
where specifically are you seeing this issue? I'm not seeing the string "D:\ in the markdown Instruction files for lab 1
rgds
Marcin

**Comment by renaudwangler** [comment]
I See it everywhere in the resultant doc files (maybe my example was bad, since the module 01 doesn't call any labfiles sorry : read D:\ in module 2 to 11 instead...)

**Comment by polichtm** [comment]
Pls provide specific example (markdown file names and the corresponding line numbers)
thnx
Marcin

**Comment by renaudwangler** [comment]
Hi.... This problem is in nearly every module :(
Last time we met it this morning in module 5 : 
Student must pick .sln files to upload the webApp.
In the file "20533C_LAB_AK_05.md" on exercice 2, Task 1, point 5 we can read "Browse to the folder D:\LabFiles\Lab05\Starter\AdatumWebsite, click[...],
In the same file on exercice 3, task 1 point 8 we can read "Browse to the folder D:\LabFiles\Lab05\Starter\NewAdatumWebsite."

In the "20533C_LAB_AK_05.docx" generated by the pandoc.ps1 script, both of these line state
"Browse **D:05*" (without quotes).

This problem is seen in every module of the course and becomes critical in some ones like the example I provided here.

Nota : I used the recommanded versions (not the latest ones) of the tools needed to generate the doc files.

Thanks again for your valuable help :)

**Comment by polichtm** [comment]
Apparently this is an unintended side effect of how pandoc.ps1 parses special characters in markdown. I removed the bold font formatting from the path in 20533C_LAB_AK_05.docx - are you in the position to regenerate the corresponding docx and verify whether this made the difference? If not, I'll test it later today
rgds
Marcin

**Comment by renaudwangler** [comment]
Justed gave a try with you change... no luck... same result : the doc contains "D:05" (without bold chars of course this time)

**Comment by renaudwangler** [comment]
Just try somethong else : The problem is with the backslash sign : I escaped the backslash sign (by doubling it) and no more problem...
I don't know if this solution is acceptable but suggest you to try it out ;)

(tried it with the path strings in modules 1 and 5 and everything went fine, including the bold chars).

Sample : I replaced "D:\Labfiles\Lab02\Starter\New-AzureRm20533C02VM.ps1" with "D:\\Labfiles\\Lab02\\Starter\\New-AzureRm20533C02VM.ps1" in the file "20533C_LAB_02.md"

**Comment by polichtm** [comment]
There are actually several entries that contain the string D:\ in markdown-formatted instructions for lab 1 - e.g. 20533C_LAB_01.md: 

Task 2: Manage Azure resources and resource groups by using Azure PowerShell
In the Windows PowerShell ISE window, open the D:\Labfiles\Lab01\Starter\Start-AzureRm20553C01Lab.ps1 file.

Are you seeing the same issue in the docx file for these instructions? 

thnx
Marcin

**Comment by renaudwangler** [comment]
Hi
As I tald you, the problem appears in the docx files everytime the "\" char is used :(
In the 20533C_LAB_01.md, I had to escape the \ in 3 different places.

This morning, students were unable to read the username in the 20533C_LAB10_AK.md since it's written "ADATUM\Student" ==> The docx shows us a "ADATUM*" username...

I think we finally (I had the same problem in the 10979 course) found a cure ;)

**Comment by polichtm** [comment]
Hi - the reason I asked is that it seemed that you indicated that the problem does not exist in the first markdown file. In any case, I added the escape character across all files.
thnx
Marcin
