### ISSUE TITLE
Problems with the DeployAzureDSC.ps1

### ISSUE THREAD

**Issue by marciogmorales** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#149]
We´re having trouble with the script "Labfiles\Lab04\Starter\DeployAzureDSC.ps1"

Error:

WARNING: The output object type of this cmdlet will be modified in a future release.
New-AzureRmStorageAccount : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not 
null or empty, and then try the command again.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:24 char:89
+ ... geAccount -ResourceGroupName $resourceGroupName -Name $saName -Type $ ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureRmStorageAccount], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Management.Storage.NewAzureStorageAccountCommand
 
New-AzureStorageContext : Cannot validate argument on parameter 'StorageAccountKey'. The argument is null or empty. Provide an argument 
that is not null or empty, and then try the command again.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:35 char:117
+ ... orageAccount.StorageAccountName -StorageAccountKey $storageAccountKey
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureStorageContext], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext
 
New-AzureStorageContainerSASToken : Could not get the storage context.  Please pass in a storage context or set the current storage context.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:36 char:13
+ $sasToken = New-AzureStorageContainerSASToken -Name $containerName -C ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureStorageContainerSASToken], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStorageContainerSasToke 
   nCommand
 
Set-AzureRmVMExtension : Can not perform requested operation on nested resource. Parent resource 'ResDevWebVM1' not found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : ''
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:51 char:1
+ Set-AzureRmVMExtension  -ResourceGroupName $resourceGroupName -VMName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand
 
Set-AzureRmVMExtension : Can not perform requested operation on nested resource. Parent resource 'ResDevWebVM2' not found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : ''
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:55 char:1
+ Set-AzureRmVMExtension  -ResourceGroupName $resourceGroupName -VMName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand

**Comment by polichtm** [comment]
pls download the most recent version
