### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by augustofreitass** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#150]
Hi,

We´re are found an issue on this scritpt when using in the 20533 Training class LAB04, see bellow:

New-AzureRmStorageAccount : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the 
command again.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:24 char:89
+ ... geAccount -ResourceGroupName $resourceGroupName -Name $saName -Type $ ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureRmStorageAccount], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Management.Storage.NewAzureStorageAccountCommand
 
Get-AzureRmStorageAccountKey : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try 
the command again.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:25 char:95
+ ... StorageAccountKey -ResourceGroupName $resourceGroupName -Name $saName
+                                                                   ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzureRmStorageAccountKey], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountKeyCommand
 
New-AzureStorageContext : Cannot validate argument on parameter 'StorageAccountKey'. The argument is null or empty. Provide an argument that is not null or empty, and 
then try the command again.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:34 char:117
+ ... orageAccount.StorageAccountName -StorageAccountKey $storageAccountKey
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureStorageContext], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext
 
New-AzureStorageContainerSASToken : Could not get the storage context.  Please pass in a storage context or set the current storage context.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:35 char:13
+ $sasToken = New-AzureStorageContainerSASToken -Name $containerName -C ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureStorageContainerSASToken], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStorageContainerSasTokenCommand

Thanks in advance!

**Comment by polichtm** [comment]
pls download the latest version of the script
