### ISSUE TITLE
Setup Azure - Module 10

### ISSUE THREAD

**Issue by marciogmorales** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#153]
Hi,
I just found with my students a common error when we´re trying to run Setup-Azure for Module 10.

A error occur in the: VERBOSE: 1:46:28 PM - Checking deployment status in 5 seconds
VERBOSE: 1:46:35 PM - Resource Microsoft.Compute/virtualMachines/extensions 'adVM/CreateADForest' provisioning status is running
VERBOSE: 1:57:22 PM - Checking deployment status in 5 seconds
VERBOSE: 1:57:29 PM - Checking deployment status in 5 seconds
VERBOSE: 1:57:38 PM - Checking deployment status in 5 seconds
VERBOSE: 1:57:46 PM - Checking deployment status in 5 seconds
New-AzureRmResourceGroupDeployment : A task was canceled.
At D:\Labfiles\Lab10\Starter\Setup-20533C10Lab.ps1:109 char:5
Log Attached.

Active Directory Domain Services was installed, but without any AD DS Tools (like mmc), so for some students it´s very importante that this feature came up installed.

[Setup-Azure-10.zip](https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/files/962942/Setup-Azure-10.zip)

**Comment by polichtm** [comment]
Is AD DS domain set up? If so, then this happens to be the intended outcome - AD DS tools are not installed - the lab guide takes students through steps that describe how to use Windows PowerShell to manage AD. Students are obviously free to install AD tools if that's what they prefer
thnx
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
