### ISSUE TITLE
M20533C Setup-Azure failing for Mod 10

### ISSUE THREAD

**Issue by PurvesG** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#158]
## !! Setup-Azure is failing for Mod 10 !!
<# Setup-20533C10Lab.ps1 Line 49 Get-AzureRmContext is returning a NULL value
Student Work around
Replace the 'stage' + ((Get-AzureRmContext).Subscription.SubscriptionId).Replace('-', '').substring(0, 19)
with 'stage##############' where ############## is the first 14 characters of your subscription ID with the “-“removed 
i.e. 'stage696342e19c6449'
#>

**Comment by polichtm** [comment]
I just rerun this script and it completes successfully without any errors. 
Pls post the output of Get-AzureRmContext

**Comment by PurvesG** [comment]
I went back and verified. It seems if you install the current Azure PowerShell Modules that the errors arise.I ran the scripts on the MIA-CL1 VM with the old Azure and msonline modules installed and they ran without error.Then I ran the current installer and reran the scripts and they errored out.   https://azure.microsoft.com/en-us/downloads/ 
It appears as if Microsoft may have changed some output parameters.
I have attached the error output.The errors in the Show-SubscriptionARM.psm1 were non fatal and could be corrected by changing    Set-AzureRmContext -SubscriptionId $subs[0].SubscriptionIdto    Set-AzureRmContext -SubscriptionId $subsThis would probably fail if there were more than one subscription, 
The error on the Setup-20533C10Lab.ps1 was fatal and the script created nothing, again NULL returns.

 <# Setup-20533C10Lab.ps1 Line 49 Get-AzureRmContext is returning a NULL value



Student Work around
Edit: D:\Labfiles\Lab10\Starter\Setup-20533C10Lab.ps1
Locate: Line 49
Replace: 'stage' + ((Get-AzureRmContext).Subscription.SubscriptionId).Replace('-', '').substring(0, 19)
With: 'stage##############' 
 where ############## is the first 14 characters of your subscription ID with the “-“removed 
 i.e. 'stage696342e19c6449'
#> 




 I also tested on a VM where the AzureRM module had been installed after the Azure modules and there were a series of command does not exist errors.  

I guess the work around is the revert the MIA-CL1 VM if any of the new PowerShell modules get loaded.

**Comment by polichtm** [comment]
There is a new release of Azure PowerShell every few weeks - there is no realistic possibility to update every script in the course to account for potential incompatibilites. 
Pls make sure to use the version that is included in the VM
thnx
Marcin
