### ISSUE TITLE
Lab 9 Classic portal won't open new directory

### ISSUE THREAD

**Issue by HollyDickson** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#159]
Lab9, Ex1, Task 2 fails with a message: None of your subscriptions are viewable in the directory
You have no subscriptions in the adatum170617.onmicrosoft.com directory that can be viewed in the classic portal. View all your subscriptions in the Azure portal (The best experience) or continue with the classic portal to view subscriptions in other directories.

The Premium trial can be activated from quick start in the new portal. The users and groups can be created, but the procedure is completely different. Making Karen a global admin is different. Assigning the Premium licences is different. 

The whole lab needs rewriting if the Classic Portal is no longer available for the lab. (Or do I just have a bug?)
Shouldn't we be using the new portal anyway, whenever possible?

**Comment by polichtm** [comment]
At this point, working with Azure AD still involves using multiple interfaces (e.g. MFA). We will be updating the content of the lab to account for the functionality available in the Azure portal wherever applicable
thnx
Marcin

**Comment by polichtm** [comment]
Updated
