### ISSUE TITLE
Lab 2 vpn connection

### ISSUE THREAD

**Issue by mrstage** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#160]
After creating the Virtual network gateway and copying the public key into it, I downloaded the VPN client only to have it sit there verifying the password then timing out. This is occurring on all machines.

**Comment by polichtm** [comment]
Pls review the comments section at https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-point-to-site-resource-manager-portal and verify whether the issues described there are not applicable in your case
thnx
Marcin

**Comment by mrstage** [comment]
This seems to be the current solution. Worked for me first time.
Thanks for the response.

https://social.msdn.microsoft.com/Forums/en-US/572c1a71-eba0-4b47-a9d9-755a3c3939af/error-opening-point-to-site-vpn?forum=WAVirtualMachinesVirtualNetwork
