### ISSUE TITLE
Setup-Azure (Module 3)

### ISSUE THREAD

**Issue by marciogmorales** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#161]
We´re facing problems with the preparetion of the Lab3. (error log attached).

Me and my students already update the Azure PowerShell and the files (Scripts) with the image of MIA-CL10

[Setup-Azure-3.zip](https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/files/1093314/Setup-Azure-3.zip)

**Comment by polichtm** [comment]
Could you clarify where you what gave you the idea to update the Azure PowerShell?
You are not supposed to do this.
There is a new release of Azure PowerShell every few weeks - there is no realistic possibility to update every script in the course to account for potential incompatibilites. 
Pls make sure to use the version that is included in the VM
thnx
Marcin

**Comment by marciogmorales** [comment]
Just to clarify... you guys told me to upadte my Azure PowerShell last course (May), because new command´s came on.


The test with the default Azure Powershell (VM`´s) doesn´t work either.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
De: polichtm <notifications@github.com>
Enviado: quinta-feira, 22 de junho de 2017 00:30
Para: MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions
Cc: marciogmorales; Author
Assunto: Re: [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions] Setup-Azure (Module 3) (#161)


Could you clarify where you what gave you the idea to update the Azure PowerShell?
You are not supposed to do this.
There is a new release of Azure PowerShell every few weeks - there is no realistic possibility to update every script in the course to account for potential incompatibilites.
Pls make sure to use the version that is included in the VM
thnx
Marcin
