### ISSUE TITLE
Migrate PowerShell Lab Modules to AzureRM

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#162]
Not only is the classic model obsolete, the setup will be as simple as `Install-Module -Name AzureRM`.

I started working on this myself however it is quite a large job and I don't have the time.

**Comment by polichtm** [comment]
Most of the labs are already using ARM exclusively - we're planning on applying the same change to others with the next revision of the course.

**Comment by polichtm** [comment]
Grant,
would you mind clarifying what is the specific issue you are running into?
thnx
Marcin

**Comment by grantcarthew** [comment]
At the moment the course Virtual Machine is running with both the Classic and ARM PowerShell cmdlets. As an example the [Create-Storage](https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/blob/master/Allfiles/Modules/Create-Storage/Create-Storage.psm1) function is calling `New-AzureStorageAccount` rather than `New-AzureRmStorageAccount`

As we all know, Classic Azure resources have mostly been replaced by ARM.

By migrating the 20533 Lab Module script files to the new ARM cmdlets we are bringing the setups scripts and functions inline with the courseware which is mostly focused on the ARM features.

Just to clarify, this issue is not about the courseware content, it is about the lab setup modules. I have changed the title to be more accurate.

This is a task that needs to be done. I don't think there is an option to say it is not warranted.

As with all issue tracking systems, leave this open until the issue is resolved.

**Comment by polichtm** [comment]
Grant,
appreciate the clarification, however, pls note the following:
- while the course is supposed to prepare for the exam, it does not mean that the course cannot include the material that is not covered on the exam. The classic deployment model should not be used for any new deployments, however, that does not mean that there are no existing classic deployments in Azure. The question is whether it is warranted to include limited coverage of the classic deployment model so they are in the position to support them.
- the module scripts facilitate labs, which in some cases required creation of classic resources. That's the reason for the Create-Storage module. 
- as you stated, this is not about the courseware content - but lab setup modules - effectively it's not something that students need to be concerned anyway (as long as the setup is fully functional). However, we _are_ considering eliminating the classic content - although given the points above, I'd hardly consider this to be an "issue". 
rgds
Marcin

**Comment by grantcarthew** [comment]
Ok fair enough. Thanks for the feedback @polichtm 

I must admit part of my motivation to post this issue was about using the PowerShell Gallery with `Install-Module -Name AzureRm`.

So at some point this will happen. Thanks again.
