### ISSUE TITLE
Publish the PowerShell modules into the PowerShell Gallery

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#163]
This course setup should be as simple as this:

*   `Install-PackageProvider -Name NuGet`
*   `Install-Module -Name AzureRM` <= dependent on #162 
*   `Install-Module -Name M20533` <= any name you like here
*   Go to the [Vistual Studio](https://www.visualstudio.com/) site and download the Community version.

Finally the instructor provides the `AllFiles` package.

This would enable the course to be run on a Windows 10 or Windows Server 2016 operating system without the need for a Virtual Machine. I am not suggesting removal of the Virtual Machine from the setup. It will just allow for more flexibility in the classroom environment.

Further to this it would enable remote students from home to be able to join a course using telepresence.

**Comment by polichtm** [comment]
Interesting idea - although it's not clear to me how you intend to go about testing every possible combination of OS/Azure PowerShell/Azure CLI release and keep up with their cadence. Regretfully things are rarely that simple.
In any case, appreciate your suggestions - we'll consider their viability

**Comment by polichtm** [comment]
Grant,
pls feel free to clarify how you intend to go about testing every possible combination of OS/Azure PowerShell/Azure CLI release and keep up with their cadence
rgds
Marcin

**Comment by grantcarthew** [comment]
As per the title of this issue I am suggesting publishing the 20533 course setup module scripts into the [PowerShell Gallery](https://www.powershellgallery.com/). There maybe an added benefit of being able to run the course without the Virtual Machine however this is a side effect of publishing the modules into the gallery.

I will clarify both points below:

## Publishing to the PowerShell Gallery

This is the subject of this open issue.

By using the instructions [located here](https://www.powershellgallery.com/packages/upload), anyone with a Microsoft account can publish PowerShell modules into the PowerShell Gallery. I have done this [myself recently](https://github.com/grantcarthew/GCPowerShell).

### Benefits

*   The modules will be version controlled.
*   The module installation process will be easier for the instructor and students.
*   The Microsoft 20533 course will run smoother for all involved.

### Disadvantages

After the initial publishing workflow is defined within this repository I see no disadvantages.

### Requirements

*   Define a standard course publishing name for the module. Example: MSCourse.20533
*   Publishing documentation added to this repository.
*   PowerShell Module [Manifest](https://msdn.microsoft.com/en-us/library/dd878337(v=vs.85).aspx?f=255&MSPPError=-2147217396) needs to be added.
*   Possibly publishing scripts added.
*   Completion of #165 to prevent name conflicts. Possibly worth completing #164.

## Added Benefits - Not related to this open issue

If the modules are published into the PowerShell gallery, as stated at the beginning of this issue, it would be possible to **attempt** to run the course on a Windows 10 or Windows 2016.

This is not the reason to do this though.

**Comment by polichtm** [comment]
Grant,
let me repeat my earlier question that I don't see a response to - how you intend to go about testing every possible combination of OS/Azure PowerShell/Azure CLI release and keep up with their cadence?
As you can imagine, not having an image that remains consistent introduces a wide range of support challenges. 
rgds
Marcin

**Comment by grantcarthew** [comment]
This is for use on the course Virtual Machine.

**Comment by grantcarthew** [comment]
@polichtm Please click Label on the right hand of the GitHub interface and add Enhancement.

You can add new labels here: https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/labels

**Comment by renaudwangler** [comment]
Now that all commands are in the proper format, it would really be a nice addition to create a module and publish it to the Gallery since modules can be installed in the CloudShell :
On Day 1 student use "install-module 20533D" in a cloudshell and therafter they can use the add- and remove- commands directly in the cloudshell...

**Comment by grantcarthew** [comment]
That's a great suggestion @renaudwangler. Can we get some movement on this @polichtm ?

Also an install script as in #172.

Every time I run the course now I have to create and ISO file and get the students to mount the ISO file in the MIA-CL1 vm. An install script that downloads the lab files and installs the modules from the gallery would be a major improvement on setup time. I spend most of Monday morning of the course doing setups (Skillpipe/Azure Pass/CL1 changes etc).

A workflow like this for the students is what I am talking about:

* Open PowerShell as Administrator.
* Run `Install-Module -Name MSCourse.20533E -Force`
* Run `Import-Module -Name MSCourse.20533E`
* Run `Install-20533ELabFiles` <= or something similar.

The last command would download the release files as stated in #166.

**Comment by grantcarthew** [comment]
Here is an example of the setup process I use. I made this page this week because I got sick of talking the students through it:

https://github.com/grantcarthew/notes-course/blob/master/20533/Setup.md

**Comment by polichtm** [comment]
We are looking into implementing this functionality. 
rgds
Marcin

**Comment by mikedixson** [comment]
I've been using this code to import all the modules:
$pathToModules = "C:\Users\Administrator\Downloads\20533-ImplementingMicrosoftAzureInfrastructureSolutions-master\Allfiles\Modules"
Get-ChildItem -Path $pathToModules -Recurse | foreach {Import-Module $_.Fullname -Verbose}

**Comment by grantcarthew** [comment]
This issue is not really relevant anymore due to the new `AZ-xxx` courses. Hopefully the `AZ-103` is well done. I haven't taught it yet. Will be in a couple of weeks. Good bye and good riddance `AZ-100` and `AZ-101`.
