### ISSUE TITLE
Replace the invalid PowerShell verbs with approved verbs

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#164]
See the `Get-Verb` cmdlet.

For reference: https://msdn.microsoft.com/en-us/powershell/reference/5.0/microsoft.powershell.core/functions/get-verb

**Comment by polichtm** [comment]
Appreciate the reference - we are considering updating the names of custom modules

**Comment by polichtm** [comment]
Grant,
would you mind clarifying what is the specific issue you are running into?
thnx
Marcin

**Comment by grantcarthew** [comment]
Does this need clarifying?

This is a Microsoft Official Course and the PowerShell scripts are using unapproved verbs.

**Comment by polichtm** [comment]
Grant,
I should've clarified what specifically I'm looking for. My question is whether there is a specific issue that you are running into that results from the current naming convention of modules used in this course.
It's the matter of assigning priorities on the list of changes that we intend to apply.
rgds
Marcin

**Comment by grantcarthew** [comment]
@polichtm Please click Label on the right hand of the GitHub interface and add Fix.

You can add new labels here: https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/labels

**Comment by polichtm** [comment]
resolved

**Comment by grantcarthew** [comment]
Also good to see @polichtm. Thanks.
