### ISSUE TITLE
Add a PowerShell Module Prefix

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#165]
The course PowerShell cmdlets should contain a prefix to prevent cmdlet name conflicts.

Similar to the `AzureRm` in `Add-AzureRmAccount`.

All the cmdlets in the 20533 course should look something like this:

`Reset-20533Subscription`
`New-20533StorageAccount`

You get the idea.

To add to this the cmdlet names should be a little more accurate and verbose such as my example above. The current `Create-Storage` function is actually creating a Storage Account. Hence my example of `New-20533StorageAccount`.

**Comment by polichtm** [comment]
The modules exist within the controlled environment of the lab VM. In any case, we are considering updating the names of custom modules - your suggestion is appreciated.

**Comment by polichtm** [comment]
Grant,
would you mind clarifying what is the specific issue you are running into?
thnx
Marcin

**Comment by grantcarthew** [comment]
Even within a controlled environment it is worth preventing cmdlet name conflicts.
If #163 is completed the scripts are still going to be used in a controlled environment.

More to the point, every Microsoft product has a prefix applied to the cmdlet names because they learned from their mistakes with the Exchange teams cmdlets.

Here is a perfect example from the Exchange 2016 cmdlet list. Exchange has a [Get-MobileDevice](https://technet.microsoft.com/EN-US/library/jj218706(v=exchg.160).aspx) cmdlet. You can't tell me that the  noun `MobileDevice` is never going to conflict with other cmdlets. Well, thanks to product prefixes, it will never conflict.

By adding a prefix to the 20533 course module cmdlet names we are following Microsoft's own best practices.

**Comment by polichtm** [comment]
Grant,
I should've clarified what specifically I'm looking for. My question is whether there is a _specific_ issue that you are running into that results from the current naming convention of modules used in this course.
It's the matter of assigning priorities on the list of changes that we intend to apply.
rgds
Marcin

**Comment by grantcarthew** [comment]
@polichtm Please click Label on the right hand of the GitHub interface and add Enhancement.

You can add new labels here: https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/labels

**Comment by polichtm** [comment]
resolved

**Comment by grantcarthew** [comment]
Oh, great stuff @polichtm although I don't think the version letter needed to be in the prefix. Thanks.

**Comment by grantcarthew** [comment]
@polichtm This is great that we have a prefix now however having the version letter (20533D or 20533E) in the prefix will cause issues when the modules are published into the PowerShell Gallery #163 .

As a suggestion, a script could be added to the modules such as `Get-20533Version` that would report the course version `20533E` and module version details.

Then the lab instructions and published modules will all have a prefix of `20533` rather than including the letter.

As an example: `Add-20533Environment`

**Comment by polichtm** [comment]
Appreciate the suggestion. We're looking into implementing the functionality you described
rgds
Marcin

**Comment by waliedrr** [comment]
hello 
can help me to Preparing the lab environment  how to edit in script

**Comment by polichtm** [comment]
What edit are you referring to?
rgds
Marcin
