### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#167]
Use [Pester](https://github.com/pester/Pester) and unit test the PowerShell modules.

**Comment by polichtm** [comment]
There would be a significant overhead in building the unit testing mechanism at this point. We will consider this. In the meantime, you are certainly welcome to submitting pull requests if you would like to contribute to improving the course.
