### ISSUE TITLE
Bring README up-to-date with style used on 20-532

### ISSUE THREAD

**Issue by SteGriff** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#169]
The readme is a bit ugly and hard to read due to lack of sections. I'd like to remedy this by making the style match how it is on [20-532](https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/readme.md).

**Comment by polichtm** [comment]
Appreciated - merged
