### ISSUE TITLE
Lab Provisioning Scripts

### ISSUE THREAD

**Issue by MohamedHoosen** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#173]
Hi i am doing preps for this course, the book says run the provisioning scripts before doing labs.
For Module 1 i have located Setup-Azure.psm1, i cant seem to run this script? Please help, what do i need to do to run the scrip?

**Comment by polichtm** [comment]
Mohamed,
you should be able to simply run Setup-Azure from the elevated Windows PowerShell prompt
rgds
Marcin

**Comment by MohamedHoosen** [comment]
Hi Marcin, 
Thank for your reply,

I have managed to import the Setup-Azure.psm1 into powershell
![untitled](https://user-images.githubusercontent.com/28430491/27834001-6b0dca2a-60d5-11e7-8517-20980712f848.jpg)

However when i follow the prompts i get errors. Like in the pic. 
![untitled2](https://user-images.githubusercontent.com/28430491/27834027-91b83c96-60d5-11e7-87af-0f95415cbd1f.jpg)
 
Do i need to cusomize the script, i just changed some paths in.

Please help, this should run normal, without me doing anything.

**Comment by polichtm** [comment]
Hi Mohamed,
You should not have to import anything. All necessary modules are referenced by the PSModulePath environment variable.
Are you using an image of the lab VM?
Rgds
Marcin

**Comment by MohamedHoosen** [comment]
Hi Marcin, 

Yes i am using the course vhd from the learning download center -> 20533C-MIA-CL1 vm. 

I followed the setup guide as normal, the only thing is i didnt use the NAT vm for internet, i added another Network adapter to VM, which connect directly to internet.

Regards
Mohamed

**Comment by polichtm** [comment]
Hi Mohamed,
Pls post the output of the following run from the PowerShell console:

$env:PSModlePath

$PSVersionTable

Thnx
Marcin

**Comment by edbakermct** [comment]
$env:PSModlePath  $env:PSModulePath

**Comment by MohamedHoosen** [comment]
Hi Marcin,

Thanks
I have fixed my current issue. 

Problem was on the VM, there is drive D:\ which suppose to contain all the scripts (Allfiles) for it to be auto recognized in power-shell, so when I type Setup-Azure...and so on. No import is needed.  

In the Course setup i had not noticed this. That we need to copy the LabFiles from GITHUB into the VM D drive? Maybe i had missed the instruction.

There needs to be a popper guide on the Lab-Setup aspect of the course.

Thanks alot 
![untitled3](https://user-images.githubusercontent.com/28430491/27859867-7a6dd7e4-617a-11e7-89d2-18cc17e4f6b8.jpg)

**Comment by polichtm** [comment]
Mohamed
That has been the case since the version C went live. We'll look into making this information more readily available.
rgds
Marcin

**Comment by polichtm** [comment]
that's part of the setup guide
