### ISSUE TITLE
Azure Location - Mod 2 

### ISSUE THREAD

**Issue by MohamedHoosen** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#174]
Hi 
I am working on Module 2, Get to the step to run script New-AzureRm20533C02VM.ps1 , it gives an error that the Vm cannot be created using existing azure subscription in the location Central Us. 

I am using an Azure Pass Subscription, and i am in South Africa.

Which is the Azure Data center that is closest to me, to use for this?

Please help.

Regards
Mohamed

**Comment by polichtm** [comment]
Mohamed,
pls refer to https://azure.microsoft.com/en-us/regions/offers/
rgds
Marcin
