### ISSUE TITLE
Build script deletes all generated files if Write-Zip fails

### ISSUE THREAD

**Issue by SteGriff** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#180]
Hi,

I foolishly just ran the build script `pandoc.ps1` without the PSCX installed, so the ZipFiles step failed. However, the docx files which my PC had just spent 10 mins generating got deleted anyway! 😂

So I was wondering if it would be ok with you if I put the ZipFiles and Remove-Item steps together in a `try` block so that the files aren't deleted if Zipping fails? This will allow the user to manually zip them up.

Will submit pull request if you agree

Cheers,
Ste

**Comment by polichtm** [comment]
Ste - appreciate the suggestion - we're looking into this
rgds
Marcin

**Comment by SteGriff** [comment]
Thanks Marcin,

As I said, I'm happy to implement the fix and send PR

Ste

**Comment by polichtm** [comment]
Ste - apologies for this taking so long - the change you requested has been implemented
rgds
Marcin
