### ISSUE TITLE
ExtremeLabs VM uses old password

### ISSUE THREAD

**Issue by Apoc70** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#182]
The ExtremeLabs VM uses the old default password. This should be mentioned in the documents.

**Comment by polichtm** [comment]
We'll follow up on this with Xtreme and, if needed, update the documentation
thnx
Marcin

**Comment by Apoc70** [comment]
Pls take care of updating the lab scripts as well, as the lab folders do not contain the new *RM* PowerShell lab scripts.

**Comment by polichtm** [comment]
It's not something that we control - we'll need to follow up with Xtreme
thnx
Marcin

**Comment by polichtm** [comment]
resolved
