### ISSUE TITLE
Lab 3-Exercise 3  Use Visual Studio and an Azure Resource Manager Template to Deploy ARM Virtual Machines

### ISSUE THREAD

**Issue by akmalyezdani512** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#183]
Deployment Fails with following output.

23:33:41 - Build started.
23:33:41 - Project "ResDevLinuxDeploy.deployproj" (StageArtifacts target(s)):
23:33:41 - Project "ResDevLinuxDeploy.deployproj" (ContentFilesProjectOutputGroup target(s)):
23:33:41 - Done building project "ResDevLinuxDeploy.deployproj".
23:33:41 - Done building project "ResDevLinuxDeploy.deployproj".
23:33:41 - Build succeeded.
23:33:41 - The following parameter values will be used for this deployment:
23:33:41 -     vmName: ResDevApp1
23:33:41 -     adminUsername: Student
23:33:41 -     adminPassword: <securestring>
23:33:41 -     virtualNetworkName: HQ-VNET
23:33:41 -     resourceGroupName: USServers
23:33:41 -     subnetName: App
23:33:41 -     vmSize: Standard_D1_V2
23:33:41 -     ubuntuOSVersion: 14.04.2-LTS
23:33:41 -     storageAccountType: Standard_LRS
23:33:41 - Launching deployment PowerShell script with the following command:
23:33:41 - 'd:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeploy\Scripts\Deploy-AzureResourceGroup.ps1' -StorageAccountName '' -ResourceGroupName '20533C0301-LabRG' -ResourceGroupLocation 'eastus' -TemplateFile 'd:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeploy\templates\azuredeploy.json' -TemplateParametersFile 'd:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeploy\templates\azuredeploy.parameters.json' -ArtifactStagingDirectory '..\bin\Debug\staging'
23:33:44 - Add-AzureRMAccount : Unable to find environment with name 
23:33:44 - 'Microsoft.WindowsAzure.Commands.Profile.Models.PSAzureEnvironment'
23:33:44 - At line:1 char:595
23:33:44 - + ... net/'  }; ((Add-AzureRMAccount -SubscriptionId 
23:33:44 - '217fb126-f0d9-46b1-81 ...
23:33:44 - +                 
23:33:44 - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:33:44 -     + CategoryInfo          : InvalidOperation: (:) [Add-AzureRmAccou 
23:33:44 -    nt], PSInvalidOperationException
23:33:44 -     + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Comman 
23:33:44 -    ds.Profile.AddAzureRMAccountCommand
23:33:44 -  
23:33:44 - At D:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeplo
23:33:44 - y\Scripts\Deploy-AzureResourceGroup.ps1:12 char:35
23:33:44 - +     [string] $ResourceGroupName = 'ResDevLinuxDeploy',
23:33:44 - +                                   ~~~~~~~~~~~~~~~~~~~
23:33:44 - The assignment expression is not valid. The input to an assignment 
23:33:44 - operator must be an object that is able to accept assignments, such 
23:33:44 - as a variable or a property.
23:33:44 - At D:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeplo
23:33:44 - y\Scripts\Deploy-AzureResourceGroup.ps1:16 char:38
23:33:44 - + ... ainerName = $ResourceGroupName.ToLowerInvariant() + 
23:33:44 - '-stageartifacts' ...
23:33:44 - +                 
23:33:44 - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:33:44 - The assignment expression is not valid. The input to an assignment 
23:33:44 - operator must be an object that is able to accept assignments, such 
23:33:44 - as a variable or a property.
23:33:44 - At D:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeplo
23:33:44 - y\Scripts\Deploy-AzureResourceGroup.ps1:17 char:30
23:33:44 - +     [string] $TemplateFile = '..\Templates\azuredeploy.json',
23:33:44 - +                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:33:44 - The assignment expression is not valid. The input to an assignment 
23:33:44 - operator must be an object that is able to accept assignments, such 
23:33:44 - as a variable or a property.
23:33:44 - At D:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeplo
23:33:44 - y\Scripts\Deploy-AzureResourceGroup.ps1:18 char:40
23:33:44 - + ... $TemplateParametersFile = 
23:33:44 - '..\Templates\azuredeploy.parameters.json',
23:33:44 - +                               
23:33:44 - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:33:44 - The assignment expression is not valid. The input to an assignment 
23:33:44 - operator must be an object that is able to accept assignments, such 
23:33:44 - as a variable or a property.
23:33:44 - At D:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeplo
23:33:44 - y\Scripts\Deploy-AzureResourceGroup.ps1:19 char:42
23:33:44 - +     [string] $ArtifactStagingDirectory = '..\bin\Debug\staging',
23:33:44 - +                                          ~~~~~~~~~~~~~~~~~~~~~~
23:33:44 - The assignment expression is not valid. The input to an assignment 
23:33:44 - operator must be an object that is able to accept assignments, such 
23:33:44 - as a variable or a property.
23:33:44 - At D:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeplo
23:33:44 - y\Scripts\Deploy-AzureResourceGroup.ps1:20 char:28
23:33:44 - +     [string] $AzCopyPath = '..\Tools\AzCopy.exe',
23:33:44 - +                            ~~~~~~~~~~~~~~~~~~~~~
23:33:44 - The assignment expression is not valid. The input to an assignment 
23:33:44 - operator must be an object that is able to accept assignments, such 
23:33:44 - as a variable or a property.
23:33:44 -     + CategoryInfo          : ParserError: (:) [], ParseException
23:33:44 -     + FullyQualifiedErrorId : InvalidLeftHandSide
23:33:44 -  
23:33:44 - Deploying template using PowerShell script failed.
23:33:44 - Tell us about your experience at http://go.microsoft.com/fwlink/?LinkId=691202

**Comment by polichtm** [comment]
Just tested this and, in my case, the deployment completes successfully (see below). Pls make sure that you provide/save password and choose the existing resource group (as instructed in the lab guide).

13:54:12 - The following parameter values will be used for this operation:
13:54:12 -     vmName: ResDevApp1
13:54:12 -     adminUsername: Student
13:54:12 -     adminPassword: <securestring>
13:54:12 -     virtualNetworkName: HQ-VNET
13:54:12 -     resourceGroupName: 20533C0301-LabRG
13:54:12 -     subnetName: App
13:54:12 -     vmSize: Standard_D1_V2
13:54:12 -     ubuntuOSVersion: 16.04.0-LTS
13:54:12 -     storageAccountType: Standard_LRS
13:54:13 - Build started.
13:54:13 - Project "ResDevLinuxDeploy.deployproj" (StageArtifacts target(s)):
13:54:13 - Project "ResDevLinuxDeploy.deployproj" (ContentFilesProjectOutputGroup target(s)):
13:54:13 - Done building project "ResDevLinuxDeploy.deployproj".
13:54:13 - Done building project "ResDevLinuxDeploy.deployproj".
13:54:13 - Build succeeded.
13:54:13 - Launching PowerShell script with the following command:
13:54:13 - 'D:\Labfiles\Lab03\Starter\ResDev\ResDevLinuxDeploy\ResDevLinuxDeploy\bin\Debug\staging\ResDevLinuxDeploy\Scripts\Deploy-AzureResourceGroup.ps1' -StorageAccountName '' -ResourceGroupName '20533C0301-LabRG' -ResourceGroupLocation 'southcentralus' -TemplateFile 'd:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeploy\templates\azuredeploy.json' -TemplateParametersFile 'd:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeploy\templates\azuredeploy.parameters.json' -ArtifactStagingDirectory '..\..' -DSCSourceFolder '..\DSC'
13:54:15 - 
13:54:15 - 
13:54:15 - Environment           : AzureCloud
13:54:15 - Account               : xxxxxxx@outlook.com
13:54:15 - TenantId              : 1f0e6480-89db-4b59-8c45-7a5d5555dddd
13:54:15 - SubscriptionId        : 5a37f291-b296-4c64-b53c-0ceb5555dddd
13:54:15 - SubscriptionName      : Azure Pass
13:54:15 - CurrentStorageAccount : 
13:54:15 - 
13:54:16 - VERBOSE: Performing the operation "Replacing resource group ..." on target "".
13:54:17 - VERBOSE: 1:54:17 PM - Created resource group '20533C0301-LabRG' in location 'southcentralus'
13:54:17 - 
13:54:17 - ResourceGroupName : 20533C0301-LabRG
13:54:17 - Location          : southcentralus
13:54:17 - ProvisioningState : Succeeded
13:54:17 - Tags              : 
13:54:17 - TagsTable         : 
13:54:17 - ResourceId        : /subscriptions/5a37f291-b296-4c64-b53c-0ceb457001a3/resourceGroups/20533C0301-LabRG
13:54:17 - 
13:54:18 - VERBOSE: Performing the operation "Creating Deployment" on target "20533C0301-LabRG".
13:54:20 - VERBOSE: 1:54:20 PM - Template is valid.
13:54:21 - VERBOSE: 1:54:21 PM - Create template deployment 'azuredeploy-0730-2054'
13:54:21 - VERBOSE: 1:54:21 PM - Checking deployment status in 5 seconds
13:54:27 - VERBOSE: 1:54:27 PM - Resource Microsoft.Storage/storageAccounts 'resdevapp1dnod2apmhhrqm' provisioning status is 
13:54:27 - running
13:54:27 - VERBOSE: 1:54:27 PM - Checking deployment status in 15 seconds
13:54:42 - VERBOSE: 1:54:42 PM - Resource Microsoft.Network/networkInterfaces 'nicresdevapp1' provisioning status is succeeded
13:54:42 - VERBOSE: 1:54:42 PM - Resource Microsoft.Network/publicIPAddresses 'publicipresdevapp1' provisioning status is 
13:54:42 - succeeded
13:54:43 - VERBOSE: 1:54:43 PM - Checking deployment status in 5 seconds
13:54:48 - VERBOSE: 1:54:48 PM - Checking deployment status in 5 seconds
13:54:53 - VERBOSE: 1:54:53 PM - Resource Microsoft.Compute/virtualMachines 'ResDevApp1' provisioning status is running
13:54:53 - VERBOSE: 1:54:53 PM - Resource Microsoft.Storage/storageAccounts 'resdevapp1dnod2apmhhrqm' provisioning status is 
13:54:53 - succeeded
13:54:53 - VERBOSE: 1:54:53 PM - Checking deployment status in 5 seconds
13:54:59 - VERBOSE: 1:54:59 PM - Checking deployment status in 5 seconds
13:55:04 - VERBOSE: 1:55:04 PM - Checking deployment status in 5 seconds
13:55:10 - VERBOSE: 1:55:10 PM - Checking deployment status in 5 seconds
13:55:15 - VERBOSE: 1:55:15 PM - Checking deployment status in 5 seconds
13:55:21 - VERBOSE: 1:55:21 PM - Checking deployment status in 5 seconds
13:55:29 - VERBOSE: 1:55:26 PM - Checking deployment status in 5 seconds
13:55:35 - VERBOSE: 1:55:35 PM - Checking deployment status in 5 seconds
13:55:40 - VERBOSE: 1:55:40 PM - Checking deployment status in 5 seconds
13:55:46 - VERBOSE: 1:55:46 PM - Checking deployment status in 5 seconds
13:55:51 - VERBOSE: 1:55:51 PM - Checking deployment status in 5 seconds
13:55:57 - VERBOSE: 1:55:57 PM - Checking deployment status in 5 seconds
13:56:05 - VERBOSE: 1:56:03 PM - Checking deployment status in 5 seconds
13:56:10 - VERBOSE: 1:56:10 PM - Checking deployment status in 5 seconds
13:56:15 - VERBOSE: 1:56:15 PM - Checking deployment status in 5 seconds
13:56:21 - VERBOSE: 1:56:21 PM - Checking deployment status in 5 seconds
13:56:28 - VERBOSE: 1:56:26 PM - Checking deployment status in 5 seconds
13:56:33 - VERBOSE: 1:56:33 PM - Checking deployment status in 5 seconds
13:56:38 - VERBOSE: 1:56:38 PM - Checking deployment status in 5 seconds
13:56:44 - VERBOSE: 1:56:44 PM - Checking deployment status in 5 seconds
13:56:50 - VERBOSE: 1:56:50 PM - Checking deployment status in 5 seconds
13:56:55 - VERBOSE: 1:56:55 PM - Checking deployment status in 5 seconds
13:57:00 - VERBOSE: 1:57:00 PM - Checking deployment status in 5 seconds
13:57:06 - VERBOSE: 1:57:06 PM - Resource Microsoft.Compute/virtualMachines 'ResDevApp1' provisioning status is succeeded
13:57:06 - VERBOSE: 1:57:06 PM - Checking deployment status in 5 seconds
13:57:12 - 
13:57:12 - DeploymentName          : azuredeploy-0730-2054
13:57:12 - CorrelationId           : 166245da-dfa3-4836-904a-e0aec9c751e2
13:57:12 - ResourceGroupName       : 20533C0301-LabRG
13:57:12 - ProvisioningState       : Succeeded
13:57:12 - Timestamp               : 7/30/2017 8:57:06 PM
13:57:12 - Mode                    : Incremental
13:57:12 - TemplateLink            : 
13:57:12 - TemplateLinkString      : 
13:57:12 - DeploymentDebugLogLevel : 
13:57:12 - Parameters              : {[vmName, Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], 
13:57:12 -                           [adminUsername, 
13:57:12 -                           Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], 
13:57:12 -                           [adminPassword, 
13:57:12 -                           Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], 
13:57:12 -                           [virtualNetworkName, 
13:57:12 -                           Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable]...}
13:57:12 - ParametersString        : 
13:57:12 -                           Name             Type                       Value     
13:57:12 -                           ===============  =========================  ==========
13:57:12 -                           vmName           String                     ResDevApp1
13:57:12 -                           adminUsername    String                     Student   
13:57:12 -                           adminPassword    SecureString                         
13:57:12 -                           virtualNetworkName  String                     HQ-VNET   
13:57:12 -                           resourceGroupName  String                     20533C0301-LabRG
13:57:12 -                           subnetName       String                     App       
13:57:12 -                           vmSize           String                     Standard_D1_V2
13:57:12 -                           ubuntuOSVersion  String                     16.04.0-LTS
13:57:12 -                           storageAccountType  String                     Standard_LRS
13:57:12 -                           
13:57:12 - Outputs                 : 
13:57:12 - OutputsString           : 
13:57:12 - 
13:57:12 - 
13:57:12 - 
13:57:12 - Successfully deployed template 'templates\azuredeploy.json' to resource group '20533C0301-LabRG'.

**Comment by polichtm** [comment]
closed due to lack of response
