### ISSUE TITLE
Error in execute pandoc.ps1

### ISSUE THREAD

**Issue by GitHubMarcelo** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#184]
New-Object : Retrieving the COM class factory for component with CLSID {00000000-0000-0000-0000-000000000000} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
At **C:\20533-ImplementingMicrosoftAzureInfrastructureSolutions-master\Build\pandoc.ps1**:21 char:13
+     $Word = New-Object -ComObject Word.Application
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
    + FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by grantcarthew** [comment]
Do you have Word installed on the system you are building from @GitHubMarcelo ?
