### ISSUE TITLE
Lab 07 setup-azure

### ISSUE THREAD

**Issue by dsuper123** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#186]
The script fails with not enough permissions

Steps to reproduce:
* Run setup azure
* Choose lab 7

How to solve:
* Start SQL management Studio
* Connect to local database as sa (sa / Pa55w.rd)
* Create a new login as MIA-CL1\admin as user and marked as sysadmin or more
* Run setup azure again

**Comment by polichtm** [comment]
You should be running Setup-Azure as Student within a elevated Windows PowerShell session. The student account is a local admin - it has sa privileges on the SQL Server level

**Comment by normandk** [comment]
Logged in as mia-cl1\Student, the script runs as expected.

**Comment by polichtm** [comment]
pls make sure to use the correct user account (as specified in the instructions)
