### ISSUE TITLE
SQL code format issue during pandoc export

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#192]
Hello.

I noticed a problem with the quoted SQL code in the instruction file (I just saw it with a student in the  module 7 (file "20533C_LAB_AK_07.md").
I used the recommended procedure and softs to generate the doc files and the quoted SQL code in the result has lost the "New Line" informations.
Example : exercice 2 task 2 point 5 the SQL code should read 
CREATE USER SalesApp
FOR LOGIN SalesApp
WITH DEFAULT_SCHEMA = dbo
GO
EXEC sp_addrolemember 'db_owner', 'SalesApp'
GO

and in the Word file it reads : 
CREATE USER SalesApp FOR LOGIN SalesApp WITH DEFAULT_SCHEMA = dbo GO EXEC sp_addrolemember 'db_owner', 'SalesApp' GO

**Comment by renaudwangler** [comment]
The same problem seems to happen in many places.
For instance on LAB 8 the $username and $securepassword have lost their "$" in the $credential= command (exercice 2, task2, 4).

**Comment by polichtm** [comment]
this has been resolved
