### ISSUE TITLE
Up-to-date demonstrations for MCTs

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#2]
How about adding the demonstrations to github? Demonstration also need to be up-to-date during classroom training. As an example: the OMS demonstration in Module 11 was already outdated in 3 days after the offical release of the C version.Operation Insights are now part of the new portal.

**Comment by polichtm** [comment]
From what I understand, the new approach to demos is to include only either high level step or a reference to an existing documentation that provides equivalent description. Would you find this sufficient?

Rgds

Marcin

**Comment by molenaar** [comment]
I will wait for the updated manual to see whats the new approach. For now it was just a suggestion. Accurate and up-to-date manuals are important for both students and teachers.

**Comment by polichtm** [comment]
Marcel - which specific demos are you looking for updates to?

 

Thnx

Marcin

**Comment by molenaar** [comment]
I agree that the demos are more high-level described in Skillpipe.
For now only Module 11 - Lesson 1 – Demo “Create Operational Insights workspace” is moved to the new portal. It is better to go to the new portal, select Log Analytics (OMS) and click Add to create an OMS Workspace. After creating the workspace, the quick start is also changed.

Marcel

**Comment by polichtm** [comment]
Marcel – agreed – I’ll be updating the demo steps and posting them here…

Thnx

Marcin
