### ISSUE TITLE
stuck with configuring git

### ISSUE THREAD

**Issue by getshubham** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#205]
Whenever I am executing the following command 
git clone https://github.com/MicrosoftLearning/DEV237x_Web_Front-End_Orientation.git.

it says Repository not found.

**Comment by polichtm** [comment]
Could you clarify what this has to do with 20533?
thnx
Marcin

**Comment by getshubham** [comment]
Actually I am taking a course on edx.org by Microsoft. It is related to it .

**Comment by polichtm** [comment]
Just to make sure I understand - does this mean that this is not related in any way to 20533? If so, pls follow up with the edx.org support team
thnx
Marcin

**Comment by getshubham** [comment]
Ok. Thanks for replying.

Sent from Mail for Windows 10

From: polichtm
Sent: 02 October 2017 20:57
To: MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions
Cc: getshubham; Author
Subject: Re:[MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions]stuck with configuring git (#205)

Just to make sure I understand - does this mean that this is not related in any way to 20533? If so, pls follow up with the edx.org support team
thnx
Marcin
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
