### ISSUE TITLE
20533D x Exam Topics

### ISSUE THREAD

**Issue by marciogmorales** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#207]
Hi,
Recently i just downloaded the new content of the course 20533D and realese that some topics like Azure SQL was removed and Container Service came.

But if we take a look at the new version, some topics isn´t cover any more and is necessary to pass the exam: https://www.microsoft.com/pt-br/learning/exam-70-533.aspx (example: Azure SQL)

**Comment by tiagocostapt** [comment]
If you look at the same page but in English US, there is no more reference to SQL Databases on the exam topics. https://www.microsoft.com/en-us/learning/exam-70-533.aspx

**Comment by marciogmorales** [comment]
Yeah... Exam Updated 17/10 ... Brazilian site isn´t update.

**Comment by marciogmorales** [comment]
Tests in PT-BR will be reference to older content or the new one?

**Comment by tiagocostapt** [comment]
I take exams only in English, so really don't know anything about that. I will try to investigate and get back if I have any news.

**Comment by marciogmorales** [comment]
I´ll appreciate... thank´s a lot.

**Comment by polichtm** [comment]
This should be updated within the next couple of weeks
