### ISSUE TITLE
Module 3 Unable to open project

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#211]
Lab image seems to have a clean installation of Visual Studio without the Azure SDK installed.
You can update Visual Studio by using the installer. 

Make sure you don't overwrite the Azure PowerShell modules. The lab image has version 4.3.1 of Azure and AzureRM installed. The Visual Studio installer could replace the modules with the 2.1.0 version and the scripts in the labs will not work anymore.

**Comment by polichtm** [comment]
Marcel,
that should not be the case - the image should include VS with Azure SDK.
Can you clarify where you are obtaining the image from?
thnx
Marcin

**Comment by molenaar** [comment]
That labhoster has updated the image this week. Everything is fine now.

thanx
