### ISSUE TITLE
Module 6 Lab Issue

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#217]
Module 6, the lab asks the delegate to run a powershell script E:\Labfiles\Lab06\Starter\New-20533D06FileShare.ps1. The file in that folder is called New-20533C06FileShare.ps1 and references a resource group 20533C0602-labRG. The setup script creates a resource group 20533D0602-labRG

The script file needs renaming and the powershell script modified to reference 20533D-labRG

**Comment by polichtm** [comment]
resolved
