### ISSUE TITLE
Module 7 Lab B

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#227]
az acs create --orchestrator-type kubernetes --resource-group 20533D0704-LabRG --name 20533D0704-k8scluster --generate-ssh-keys runs fine and creates the objects

az acs kubernetes get-credentials --resource-group 20533D0704-LabRG --name 20533D0704-k8scluster, then fails, specifies that the config file does not exist

**Comment by polichtm** [comment]
pls provide a screenshot of the error message you're seeing

**Comment by tinohasbach** [comment]
[cid:image001.png@01D34904.C8232680]


Hi, none of my students had an MFA button on this side. The only way was to activate MFA via the classic portal.
Robert
MCT Cologne - Germany


Von: polichtm [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. Oktober 2017 17:58
An: MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions <20533-ImplementingMicrosoftAzureInfrastructureSolutions@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions] Module 7 Lab B (#227)


pls provide a screenshot of the error message you're seeing

**Comment by renaudwangler** [comment]
Hello.
Same here today : the portal is currently evolving on this topic I guesd


Renaud WanglerFormateurIb - groupe CEGOStél. +33/0 6 83 00 77 14
Envoyé depuis mon smartphone, merci pour votre indulgence...
-------- Message d'origine --------De : tinohasbach <notifications@github.com> Date : 19/10/2017  18:05  (GMT+01:00) À : MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions <20533-ImplementingMicrosoftAzureInfrastructureSolutions@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : Re: [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions] Module 7 Lab B (#227) 
[cid:image001.png@01D34904.C8232680]








Hi, none of my students had an MFA button on this side. The only way was to activate MFA via the classic portal.


Robert


MCT Cologne - Germany








Von: polichtm [mailto:notifications@github.com]


Gesendet: Donnerstag, 19. Oktober 2017 17:58


An: MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions <20533-ImplementingMicrosoftAzureInfrastructureSolutions@noreply.github.com>


Cc: Subscribed <subscribed@noreply.github.com>


Betreff: Re: [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions] Module 7 Lab B (#227)








pls provide a screenshot of the error message you're seeing

**Comment by tonycook2** [comment]
This is a screenshot of the error 
![az acs](https://user-images.githubusercontent.com/32900473/31819901-ac6ebbf8-b596-11e7-97b7-051558aedfb3.png)

**Comment by polichtm** [comment]
The issue and workarounds/upcoming resolution are described in https://github.com/Azure/azure-cli/issues/4587
Marcin

**Comment by polichtm** [comment]
As far as I can tell, this has been resolved.
