### ISSUE TITLE
Module 9 Lab Exercise 3

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#228]
Step 4. Click All Users - the admin console does not have Multi Factor Authentication link

If you click the users panel on the right hand side, click ...More, you will see Multi Factor Authentication

**Comment by polichtm** [comment]
Do you mean that you're not seeing this?
![image](https://user-images.githubusercontent.com/10284906/31780644-4d2e223c-b4c4-11e7-8b1c-f79993ccf0fd.png)
If so, is the issue that your browser page is simply not maximized?

**Comment by tonycook2** [comment]
No, that's not what I am seeing and it is nothing to do with the screen being maximized. If you select Azure Active Directory, Users and Groups, All Users - you do not get Multi Factor Authentication in the list of options. This is a screenshot of what you see.

![all users](https://user-images.githubusercontent.com/32900473/31811009-d6f85ecc-b575-11e7-9471-5ee4a259761d.png)

If you select Azure Active Directory, Users and Groups and select the Users panel on the right, I see what you have in your screen, when I maximize it

**Comment by polichtm** [comment]
I assume that you can access the multi-factor authentication settings via the Azure classic portal (from the active directory page of your tenant) - correct? If so, pls use this as a workaround for the time being
thnx
Marcin

**Comment by polichtm** [comment]
updated steps to provide an alternative approach
