### ISSUE TITLE
Missing Demo file - Mod 6

### ISSUE THREAD

**Issue by rhettwms** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#230]
In PPT slide notes (slide #19, 20533D_06.pptx) the demo steps say "Open the Upload-Blobs_20533D06.ps1 file in the Demofiles\Mod06 folder..." The 20533 repo here at GitHub has only a Mod05 folder under Allfiles/Demofiles--there's no Mod06 folder--so there's no Upload-Blobs_20533D06.ps1 as far as I can see. Any idea where I can find that demo file? Thanks.
Rhett Williams, MCT

**Comment by polichtm** [comment]
Rhett,
updated 
rgds
Marcin
