### ISSUE TITLE
Lab Deployment on Linux Powershell

### ISSUE THREAD

**Issue by linuxcrash** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#234]
Using the Linux AzureRM Powershell 6.0 beta seems to fail. It would be great if the labs could be run/deployed using the Linux Powershell as it is officially supported by MS.

**Comment by polichtm** [comment]
Appreciate the feedback. The labs have not been designed to work with Linux PowerShell. We might consider this in future.
