### ISSUE TITLE
Lab 1 issues: 20533D_LAB_AK_01.md

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#250]
Ex 1   Task 3 Step 7: click Open should be click Save then click Open
Ex. 2  Task 3, Step 7: you can also just enter "tags" in the filter bar
Ex 3   Task 2 Step 2: Note that variable $rg2Name will be a new Resource Group that does not yet exist
Ex 3   Task 2 Step 6: Can click Run Selection button instead of right-click and choose Run Selection
Ex 3   Task 2 Step 10: Move operation may take several minutes
Ex 3   Task 2 Step 12: You should see the resource (route table) has moved to the new resource group
Ex 4   Task 2 Step 4: Move operation may take several minutes
Ex 4   Task 2 Step 5: You should see the resource (route table) has moved back to the original resource group
Ex 4   Task 3 Step 7: wait for script to complete. It will take several minutes.

**Comment by polichtm** [comment]
Updated. Appreciate the suggestions. Pls note that typically there are several ways to accomplish the same task within the Azure portal interface. We do not necessarily list every single one of them.
