### ISSUE TITLE
Question about VM disk max size in version D manual

### ISSUE THREAD

**Issue by travellingtrainer** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#252]
Hi,

In the old manuals the max disk size was 1TB, which is lower than VHD size, so was logical. But in this version the manual gives 4TB, but we still use VHD and not VHDX. A quick test confirms that 4Tb works.

How are we exceeding the VHD size limit of 2TB without moving to VHDX?

Thanks

**Comment by polichtm** [comment]
the maximum size of the OS disk in Azure VMs is 2 TB
the maximum size of the data disk in Azure VMs is 4 TB
Both types of disk must use the VHD format
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/about-disks-and-vhds 
rgds
Marcin
