### ISSUE TITLE
Lab 2 setup failure in South Central US

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#254]
After running **Add-20533DEnviornment** and selecting lab **2**, 6 Regional datacenters are offered. If **#2**, **South Central US** is selected, the script fails to create **20533D0201-vm1** and **20533D0201-vm2**. Both fail with the error: **"SkuNotAvailable" and "The requested size for resource...is currently not available in location 'southcentralus' for subscription..."**
_NOTE: Looks like only DS, A & B are supported; the script calls for D1._
(Same problem in later labs)

**Comment by polichtm** [comment]
Not according to https://azure.microsoft.com/en-us/regions/services/ - what subscription are you using?
thnx
Marcin

**Comment by itbland** [comment]
Azure Pass

________________________________

**Comment by itbland** [comment]
During class this week, using our Azure Pass subscriptions, here is what we (Trainer and ALL students) see when trying to create VMs in South Central US:
[cid:image001.png@01D3738D.28450030]

________________________________
