### ISSUE TITLE
Lab 2 setup failure in South Central US

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#255]
is still a problem with Azure Pass subscriptions. 
Using US East works until Lab 7, Lab 7 works with West US 2, but not US East.

**Comment by Bromeego** [comment]
I was told by my Tutor that some areas functionality gets change.
I have been currently using East US and that seems to be working fine for now :)

**Comment by itbland** [comment]
West US 2 will work (for now) for Lab 7

**Comment by Bromeego** [comment]
On Step 16 of Exercise 2 it fails because the --azure-size "Standard_A1_v2" command which is there isn't active on West US 2.
Changing it to --azure-size "Standard_B2MS" works (for now)

**Comment by itbland** [comment]
Thanks, Michael, that helps! 
The problem is that the Add script looks for the locations that have the needed VM sizes, not the locations that have those sizes available to our subscription (mostly Azure Pass). So the setup script will offer the student locations that will not work. As I recall, classic Azure PowerShell could filter by subscription & location, but RM Azure PowerShell cannot. (There is API support for this, so a custom cmdlet could be created.) As far as I know CLI has the same problem, it does not filter by subscription, just location. 
If the Add script did some error-checking, that would help. 
Or, If someone has a short PowerShell script that checks for availability of VM sizes for our subscription, that would be helpful for the MCT.

**Comment by polichtm** [comment]
itbland,
the setup script actually filters the choice of available regions if it detects an Azure Pass subscription - according to the information published at https://azure.microsoft.com/en-us/regions/offers/ 
However, it appears the the information published at https://azure.microsoft.com/en-us/regions/services/ does not reflect resource availability - at least not consistently. We are looking at a resolution - but for the time being, it's the matter of identifying the VM size which is available for a given subscription and the target region
rgds
Marcin

**Comment by itbland** [comment]
Thanks Marcin,
Can Azure support detail which sizes are available for Azure Pass in each region? The problem is not that the sizes aren’t available, it is that they aren’t available to Azure Pass – I can login with my MSDN subscription and not be limited like my Azure Pass trial subscription is.

-Eric

________________________________

**Comment by polichtm** [comment]
Hi itbland,
agreed. The mechanism that the provisioning script is based on seemed to work reliably in the past- unfortunately it appears that this is no longer the case. The checks will need to be a bit smarter - this is in the works...
rgds
Marcin

**Comment by polichtm** [comment]
Pls note that the default value designating the VM size has been temporarily removed from templates being used by the provisioning scripts. As the result, the script will prompt for the appropriate VM size, which will need to be provided by students. I managed to successfully complete the provisioning script using Standard_B2s size in South Central US (Azure Pass) but be mindful that, for the time being, you will need to determine VM size availability prior to the lab.
thnx
Marcin

**Comment by polichtm** [comment]
itbland,
regarding API support, if you are referring to https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-list-sizes-region then, as far as I can tell, this operates the same way as Get-AzureRmVMSizes, which does not appear to be helpful in this case
rgds
Marcin

**Comment by polichtm** [comment]
closing - this issue is described/addressed in #263
