### ISSUE TITLE
Lab 4 AK, Ex 1, Task 2, Step 9: Add 2nd nic to backend pool fails

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#257]
This appears to be a flaw in the portal, but when trying to add the 2nd nic to the pool, the IP address on the (already added) first nic appears to change to the IP address of the 2nd nic! Then the Pool will not save. As a work-around, Save it with one nic then run the following in PowerShell to add the second nic (there may be a nicer or shorter way to accomplish this.)
```
$nic0 = Get-AzureRmNetworkInterface -Name 20533D0401-nic0 -ResourceGroupName 20533D0401-LabRG
$nic1 = Get-AzureRmNetworkInterface -Name 20533D0401-nic1 -ResourceGroupName 20533D0401-LabRG
$LB = Get-AzureRmLoadBalancer
$Backend = GetAzureRmLoadBalancerBackendAddressPoolConfig -Name 20533D0401-ilb-bepool -LoadBalancer $LB
$nic0.IpConfigurations[0].LoadBalancerBackendAddressPools=$Backend
$nic1.IpConfigurations[0].LoadBalancerBackendAddressPools=$Backend
Set-AzureRmNetworkInterface -NetworkInterface $nic0
Set-AzureRmNetworkInterface -NetworkInterface $nic1
```

**Comment by polichtm** [comment]
appreciated - investigating
rgds
Marcin

**Comment by polichtm** [comment]
I just tested this and I managed to save the complete this successfully. 
![image](https://user-images.githubusercontent.com/10284906/34086382-556f57ee-e369-11e7-8cc4-72b890e533f2.png)
would you mind giving this another try?
