### ISSUE TITLE
Lab 7 Exercise 2 Step 6: missing word

### ISSUE THREAD

**Issue by tsfountain** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#258]
Need to add the word `<pending>` to the instruction. I wonder if because of angle brackets it got dropped in browser view?

6. Repeat step 5 until the value in the EXTERNAL-IP column for nginx-20533d0704 changes from `<pending>` to a public IP address. Note the public IP address in the EXTERNAL-IP column for nginx-20533d0704.

**Comment by Bromeego** [comment]
I have made the fix and requested a pull request for it :)

Thanks

**Comment by polichtm** [comment]
appreciated - updated
