### ISSUE TITLE
Module 7 Container Labs

### ISSUE THREAD

**Issue by sarahkong** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#261]
Today my students were unable to complete the Module 7 lab due to restrictions of the Azure Pass.  The template creates vm0 which is a v3 virtual machine, which for their subscription is not allowed.
I had all my students put in a support request to Azure asking for access to v3 vms. 
Before you could just switch regions and cross your fingers it would work but most of them tried all 4 regions and none of them work now.  If you know of another vm SKU they can use for containers that the subscription allows, please let me know.  Thank you

**Comment by polichtm** [comment]
You have to use a VM size that supports nested virtualization. This includes:
D(s)v3 series
E(s)v3 series
M series
rgds
Marcin

**Comment by sarahkong** [comment]
Understood. But the azure pass does not allow for these vm sizes. This is the problem we are facing.

**Comment by polichtm** [comment]
Let us know once you hear back from the Azure support team. In the meantime, I'll investigate what can be done on our end
thnx
Marcin

**Comment by JTomKinser** [comment]
I have a room full of students for the 20533 course using an Azure Pass.  Module 7 labs do not work because the "nested virtualization" images [D(s)v3, E(s)v3 or M series] are not allowed with the Azure Pass subscription.  I can demo the labs with my subscription.  Any suggestions to get "nested virtualization" to work for the students with Azure Pass subscriptions?

**Comment by tiagocostapt** [comment]
@JTomKinser did you tried to create the images on West Europe?

**Comment by sarahkong** [comment]
I taught his last week and the azure passes don’t work with skus   
Tried all regions. 
So I did what you’re doing just demo it with my dev subscription. 
I did tell the students that they could use their own non trial accounts to try it in the labs but I was not responsible for any problems with that. :)

**Comment by polichtm** [comment]
I just verified that v3 images are available in West Europe when using an Azure Pass subscription. Can you confirm whether you are seeing the same?
thnx
Marcin

**Comment by polichtm** [comment]
closing - this is the same issue as the one referenced by #263
