### ISSUE TITLE
apparent limitations due to azure pass or trial subscriptions

### ISSUE THREAD

**Issue by tektrainer** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#263]
It would seem that there have been some limitations placed on creating VMs of certain sizes when one is using the Azure Pass or Free Trial subscriptions. My students have been struggling with the setup scripts getting error messages that the vm sizes are unsupported for that region. When I deploy using my msdn subscription I have no issues whatsoever. Through trial and error my students have found the b and ds series seem to work the best.

**Comment by polichtm** [comment]
Pls make sure to use the updated version of the lab files. All template based deployments (with exception of those in module 7) have been updated to account for this issue. As the result, student will be prompted to provide the appropriate VM size during deployment. The lab in module 7 relies on Dv3/Ev3 VM sizes, which, from what I understand, are currently not available in Azure Pass subscriptions - a workaround is in the works. VM size availability also affects module 8 - however, in this case, changes must be made to the .csdef file - again, the fix should be available soon
thnx
Marcin

**Comment by tektrainer** [comment]
We are using the updated lab files and it does prompt but is there an official list somewhere of what sizes are available for Azure Pass subscriptions? We were only able to find out what worked through trial and error and that is a bit tedious 😊

**Comment by polichtm** [comment]
The only published information I'm aware of is that at https://azure.microsoft.com/en-us/regions/offers/
and at https://azure.microsoft.com/en-us/regions/services/. Unfortunately the availability is not consistent across subscription types

**Comment by tektrainer** [comment]
Yeah so maybe include a list with the curriculum? :)

From Alicia Townsend

On Dec 22, 2017, at 11:43 AM, polichtm <notifications@github.com<mailto:notifications@github.com>> wrote:


The only published information I'm aware of is that at https://azure.microsoft.com/en-us/regions/offers/
and at https://azure.microsoft.com/en-us/regions/services/. Unfortunately the availability is not consistent across subscription types

-

**Comment by polichtm** [comment]
Alicia,
this would work assuming that the list is static. As far as I can tell, the main reason we are running into this issue is that the availability of VM sizes (in case of Azure Pass) changes. 
But you are certainly welcome to post the sizes/regions that worked for you
rgds
Marcin

**Comment by tektrainer** [comment]
To add to my previous comment - most of the lab setup scripts prompt for which vm size to use and as I said my students found the B and DS series seemed to work the best. 
For Labs 7, we had to modify the azuredeploy.json template in e:\labfiles\lab07\starter\templates directory. We modified the vmsize to standard_F2s_v2 and put the vm in the westus2 region.

**Comment by polichtm** [comment]
Alicia - appreciate sharing this
rgds
Marcin

**Comment by pwgrmi** [comment]
Because the VMsize available to AzurePass can change at the whim of the admins, the only right answer is to look in the portal using machine variables like Location, Disks, Procs and RAM.  Then tell the students which VMsize to use.  You can count on at least one lab changing from class to class.

**Comment by steaksauce-** [comment]
I had luck using the EastUS region for all modules except containers. For that module, I ended up using WestEurope. This is using AzurePass -- haven't tried out with a trial account.

**Comment by itbland** [comment]
Here is what I found for the US in December:
[VM_Sizes.xlsx](https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/files/1621242/VM_Sizes.xlsx)
 (I use East US for all but containers, and use US West there.)

**Comment by polichtm** [comment]
appreciated

**Comment by Massimo-M** [comment]
AFAIK there's no reason to create a Nested-capable VM during the course for this lab. All Docker commands work from any VM without hyper-v role installed. I think that the script was meant to show hyper-v containers but something changed on the way and no one corrected it. :-)

**Comment by polichtm** [comment]
Massimo-M
have you tried installing Docker Toolbox for Windows on an Azure VM that does not support nested virtualization?
rgds
Marcin

**Comment by Massimo-M** [comment]
Polichtm 
Sure! I have installed it on a A2_v2 VM which does NOT support nested VM. Docker for Windows is just a set of utilities that allows for integration with a local HyperV. This integration is not mandatory, so if you install Docker CE for Windows and skip the HV integration, you can proceed with docker-machine creation and everything else.  :-)

**Comment by polichtm** [comment]
Massimo-M
valid point. I updated the instructions to reflect the location of the Docker CE for Windows. I also updated the template for module 7
rgds
Marcin
