### ISSUE TITLE
Where can we get the new PPT slides to match the new objectives

### ISSUE THREAD

**Issue by LindaChapman** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#264]
So much has been changing with the labs. Where can we get the new MCT trainer PPT slides that match the newly updated Lab Word documents? Everything seems very disjointed. I am preparing 20533 training course, and Microsoft changed the objectives yet again since the 10/12/2017 update.  But yet we (learning partners and MCTs) still don't have updated course material to reflect the new exam.

**Comment by polichtm** [comment]
Linda,
can you clarify where specifically you are seeing the disconnect between the PPT slides and the Word documents? Note that labs are no longer included in the Word documents - you access them via GitHub. The content of the course should also reflect the current OD of the exam. 
thnx
Marcin

**Comment by LindaChapman** [comment]
The MOC PowerPoint slides for the trainers are not available in GitHub and they do not match the GitHub updates. The MOC PPT trainer slides for students are old material. Can't you add the trainer PowerPoint current slides to GitHub too so everything is in one place?

**Comment by polichtm** [comment]
Linda,
GitHub is meant to be the repository for lab content (instructions, lab files) only - not the course content. Can you provide specific examples where you are seeing the content of the MOC PPT trainer slides being out of date?
thnx
Marcin

**Comment by LindaChapman** [comment]
All of the MOC MCT PPT files for 70-533 we purchased from the marketplace reflect the OLD November exam.  None of them reflect the new October 2017 exam. And Microsoft just change 70-533 again on Friday with a new exam on January.

The MOC MCT PPT marketplace course learning partners pay for 20533 is old and the labs do not match.

**Comment by polichtm** [comment]
Linda,
we'll be reviewing any discrepancies - but, in the meantime, would you mind clarifying what you mean by "the labs do not match"? The labs are no longer part of the content - they are hosted exclusively in GitHub.
thnx
Marcin

**Comment by tiagocostapt** [comment]
Hi Linda, I deliver the 20533 a lot and yes there is somethings that need some updates. Some new service plans, service name changes, etc... Something that it's easy for the updated MCT to figure it out. I'm not getting how you're getting something so different from the Exam OD.
Are you sure you're using the D version?

**Comment by LindaChapman** [comment]
Yes I am using version D.  The MCT PowerPoint deck does not include any material for the two new objectives in the exam, Manage Azure Operations and Manage Azure Identities.  And it doesn't cover really any speaking points.

**Comment by polichtm** [comment]
Manage Azure Identities is covered in modules 9 and 10.
OMS/Log Analytics and Azure Automation are covered in module 11
