### ISSUE TITLE
Lab Answer Keys refering to classic Azure Portal

### ISSUE THREAD

**Issue by henrikmai** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#267]
Specially in LAB 2
"Connect to classic Azure Portal" - it´s end of live since January 18. 2018.
Unable to finish this LAB like described.
Need to fix

**Comment by polichtm** [comment]
Which module are you referring to?
thnx
Marcin

**Comment by henrikmai** [comment]
20533C_LAB_AK_02.docx - Lab B: Configuring connectivity between IaaS v1 and IaaS v2

**Comment by polichtm** [comment]
Why are you using the version C of the course?

**Comment by henrikmai** [comment]
Because this are the files which are includes in the git repo. under Build\lab_instructions-v12.zip
But i see there are new one under instructions.
May the .zip-file should be deleted or refreshed.

Thnaks

**Comment by polichtm** [comment]
removed the old Pandoc generated files
