### ISSUE TITLE
VMSize not existing

### ISSUE THREAD

**Issue by cgauthier95870** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#268]
Hello
When we used the Add-20533Denvironment, we have a question about the vmsize. Does it normal ?
The size used a parameters who existing not. Do we need to get the information to the student or does it a missing in the parameters file ?
Cordially

**Comment by polichtm** [comment]
Pls make sure to use the most recent version of lab files. When running the provisioning scripts, students will be prompted to provide the required VM size. This will require that they first determine the availability of the VM size in the target region to which they deploy the lab environment
rgds
Marcin

**Comment by cgauthier95870** [comment]
I'm using the last version of the files. This information for th Vm size is not documented anywhere. I think it's interesting what we know this before using the module for preparing lab

**Comment by polichtm** [comment]
Currently, it is your responsibility (as the MCT for a given course) to determine the VM size that should be used for a given lab. You can determine such size fairly easily by stepping through the process of VM deployment from the Azure portal (on the Size blade, you will be able to identify which VM sizes are available in your subscription in the region you selected)
rgds
Marcin

**Comment by cgauthier95870** [comment]
I'm OK with this, but when modify as this are making, pass information to the MCT is a good idea.
We discover qith a collegue the new system....

**Comment by polichtm** [comment]
There are actually already several items regarding this very issue at https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/issues . Have you reviewed these?
rgds
Marcin

**Comment by cgauthier95870** [comment]
Yes I have read all information, but I have found any information of this.
Regards
Cedric GAUTHIER
