### ISSUE TITLE
Lab 2B Implementing Azure Virtual Networks

### ISSUE THREAD

**Issue by descalier** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#269]
Hello everyone,
When executing the script "Add-20533DEnvironment.psm1" no action happens, just open the script in TXT, can someone explain to me if something else should be done?

**Comment by tiagocostapt** [comment]
That's a PS module. You just need to call Add-20533DEnvironment under a PowerShell console.

**Comment by descalier** [comment]
Hi tiagocostapt,
Thanks for your answer.
Correct, I execute from the PowerShell console, it even runs as administrator, but it does not execute the processes of the script. In the same way, I execute the cmdlet "Set-ExecutionPolicy -ExecutionPolicy Bypass -Force"

**Comment by polichtm** [comment]
Are you using the VM image for the course?
thnx
Marcin

**Comment by descalier** [comment]
Hello polichtm,
I'm using the VM image of the course and from the MCT online lab and it's the same result.

**Comment by descalier** [comment]
Hello everyone,

Solved problem, perform the reimplementation of the image of the course MV. But now when entering the size of the virtual machine returns the error "The requested size for resource <subscription> is currently not available in location 'eastus' zones". What MV sizes are available for East US and Azure Pass subscriptions?

Thank you everyone for the help.

**Comment by polichtm** [comment]
What was the issue?
Regarding the sizes, refer to https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/issues/263

**Comment by descalier** [comment]
Apparently it was a problem with "PowerShell Community Extensions 3.2.2", verify and it is installed but I suppose that when implementing the VM of the course something was corrupted, so to reimplement the VM of the course was solved, but not to waste a lot of time Do not go into the details of the problem. Thank you.
