### ISSUE TITLE
Module 7

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#270]
hello 👍 ▶	Task 1: Create a compose file
1.	In the Remote Desktop session to 20533D0701-vm0, in the Administrator: Command Prompt window, to verify that Docker Compose is installed on the target Docker Azure VM, type the following, and then press Enter: docker-compose --version
2.	In the Administrator: Command Prompt window, type the following, and then press Enter: notepad docker-compose.yml
**3.	When prompted whether to create a new file, click Yes.
4.	In Notepad, type the following text, click File and click Save: ``` wordpress: image: wordpress links:
–	db:mysql ports:
–	8080:80**
db: image: mariadb environment: MYSQL_ROOT_PASSWORD: Pa55w.rd ```

the student try to the save the file but we dont know how to format it
so it never works
tks

**Comment by polichtm** [comment]
The instructions have been updated to properly reflect the format of the file. The file has been uploaded to the Labfiles/Lab07/Solution folder
rgds
Marcin
