### ISSUE TITLE
Lab 7 - Container / Docker in Azure VM

### ISSUE THREAD

**Issue by mdutkiewicz** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#271]
Within Lab 7 Exercice (deploying multi-conatiner app with Docker-compose, it is instructed to create the docker-compose.yml text file from Notepad, but the instructions from the Pandoc does not specify the exact schema and hierarchy structure of it. Should contain Version Tag V3 at beggining I guess, also the structure of WordPress component can not be flattened or tabbed.
Can you please provide in the lab & LAB_AK doc file the appropriate layout of that file or better provide it as a file within starter directory of lab7 for ease of understanding and experience for students ?
Thanks

**Comment by polichtm** [comment]
The file content has been updated in the instructions and uploaded to the Solutions folder
rgds
Marcin
