### ISSUE TITLE
Global experience for course delivery /attn of all MCTs

### ISSUE THREAD

**Issue by mdutkiewicz** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#272]
Dear all MCTs (and course editor),

Be aware Microsoft has definitely discontinued legacy classic access to Azure (i.e. manage.windowsazure.com), therefore all instructor guide procedures referencing to classic objects of azure are obsolete.
Only rely on new UI experience from portal.azure.com.
Skip any reference to legacy classic Azure-mentioned-items for students.

Have pleasure to deliver this technology to your attendeees.

**Comment by polichtm** [comment]
updated to account for EOL of the Azure classic portal
rgds
Marcin
