### ISSUE TITLE
Azure CLI Commands -Lab 1

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#274]
Hi Guys,

The command "az login" does not work.
The previous command "azure login" Works. Please revert to previous commands for Azure CLI to work .

**Comment by polichtm** [comment]
az login is an Azure CLI 2.0 command
azure login is the equivalent Azure CLI 1.0 command
Both should work on the lab VM as long as you have Azure CLI 2.0 and Azure CLI 1.0 installed.
pls clarify what you mean specifically by "does not work"
thnx
Marcin

**Comment by polichtm** [comment]
closing due to lack of response

**Comment by DanePillay-nel** [comment]
I meant if you are following the labs,you assume that Azure Cli is already installed,seeing as how this is a Vm Setup by microsoft. And if there is a requirement ,it is usually listed as a requirement in the lab to install it. I initially tried looking for it in Web Platform Installer and it doesn't come up. 
Also if you are self studying or attempting labs for the first time the instructions need to be tweaked a little. Specifically lab setup.There is a note of making sure lab setup is run and no command or instruction on how to do that. However there is a command to remove the environment.It would be nice if there was some consistency in that regard. Thank you though for you response. I have downloaded and installed Azure CLI 2.0 separately and it seems to work as stated in the labs,"az login".

**Comment by polichtm** [comment]
I'm glad you managed to get this resolved and appreciate the feedback. Azure CLI 1.0 and Azure CLI 2.0 are part of the VM image - can you confirm that you followed the build documentation for this course? The provisioning script (Add-20533DEnviroment) is referenced in each module in the courseware - so as long as you follow the courseware, you (as well as your students) should have the demo/lab environment configured before the lab starts. Pls let me know if this requires any additional clarification.
rgds
Marcin
