### ISSUE TITLE
Demo files for Module 8 is missing.

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#282]
The Cloud Services demo described in the ppt file requires a SmallCloudService folder containing a project. I don't find them in the version available at the moment. Several other demo files are missing throughout the course, but in those cases I can use the lab files. But not with this demo

**Comment by polichtm** [comment]
You can use the same cloud service files which are included in the lab files. Alternatively, you can leverage the sample described at https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-dotnet-get-started 
rgds
Marcin
