### ISSUE TITLE
Module 10 Lab - The specified fault domain count 3 must fall in the range of 1 to 2

### ISSUE THREAD

**Issue by aaronjthorpe** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#283]
Hi,
I'm getting an error when running Add-20533DEnvironment for Module 10 lab.  The availability set is failing to deploy with the error "The specified fault domain count 3 must fall in the range of 1 to 2".

Is there a specific region that I should be deploying this in?  I'm in Australia (not listed on my Azure Pass sub), and I've tried South East Asia and West US 2.

**Comment by aaronjthorpe** [comment]
It looks like I've worked around the problem by this section in: editing E:\Labfiles\Lab10\Starter\Templates\azuredeploy.json

```
    {

      "type": "Microsoft.Compute/availabilitySets",

      "name": "[variables('adAvailabilitySetName')]",

      "apiVersion": "2017-03-30",

      "location": "[resourceGroup().location]",

      "sku": {

        "name": "Aligned"

      },

      "properties": {

        "platformFaultDomainCount": "3",

        "platformUpdateDomainCount": "5"

      }

    },
```

And changing "platformFaultDomainCount": "2",

I then deployed a Standard_D4_v2 VM in South East Asia.

**Comment by polichtm** [comment]
I updated the template. Alternatively, you can choose the region which supports 3 fault domains. Details at https://docs.microsoft.com/en-us/azure/virtual-machines/windows/manage-availability
rgds
Marcin
