### ISSUE TITLE
Missing step in Lab 10

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#284]
In the answer key to Lab 10, exercise 2 task 1 there is a step to install ps modules: Import-Module "C:\Program Files\Microsoft AZure AD Sync\Bin\ADSync\ADSync.psd1"  
Get-ADSyncScheduler

This is not mentioned in the Lab description for Lab 10 at all, and it's pretty hard to find out for the students by themselves

**Comment by polichtm** [comment]
added
rgds
Marcin
