### ISSUE TITLE
Changes to the Azure Portal

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#288]
The Azure Portal has the following changes:
1."+New" button is now "+Create a resource" button
2."More Services" button at the bottom of the menu is now "All Services" at the top

Instructions will need to be updated accordingly.

**Comment by itbland** [comment]
Duplicate of #287 
@polichtm merged those changes last Tuesday, the code should be good for those two changes.
