### ISSUE TITLE
LAB 2 - IPForwarding grayed out

### ISSUE THREAD

**Issue by henrikmai** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#306]
Module 2 - LAB B - Exercise 2 - Task 1 - Step 6
IP Forwarding is grayed out for me and all my Students. Is there something wrong in the LAB Creation File?
If i Create a new NIC i can enable IPForwarding with the following powershell set: New-AzureRmNetworkInterface -ResourceGroupName 20533D0201-LabRG -Location westeurope -Name NIC3 -SubnetId "[...]/subnet-2" -EnableIPForwarding

**Comment by normandk** [comment]
I ran into this today as well.  To allow students to continue in the lab i
gave them these powershell instructions....


$nicConfig = Get-AzureRmNetworkInterface -ResourceGroupName
20533D0201-LabRG -Name 20533D0201-nic1

$nicConfig.EnableIPForwarding = $true

$nicConfig | Set-AzureRmNetworkInterface

**Comment by polichtm** [comment]
This is a portal interface bug - to be resolved soon
rgds
Marcin

**Comment by polichtm** [comment]
resolved
