### ISSUE TITLE
Mod 8 Demo files ALL missing

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#309]
no smallcloud service sln fil no demo files present AT all for anymodule other than mod 5 and 6

!!

**Comment by polichtm** [comment]
Ed - pls use the solution included in labfilies or follow https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-dotnet-get-started
rgds
Marcin

**Comment by edbakermct** [comment]
sorry but I can only find three .sln files in the whole e drive 

![image](https://user-images.githubusercontent.com/23341813/37763247-d6a4695e-2dbe-11e8-9004-14e9a8d81ff4.png)
so no solution present.

I forked to pre oct labs and downloaded that set of solutions.

just as an aside I really don't like the demos being the same as the labs - it adds zero value to the students.  I always do my own demos in those circumstances, but I really didn't want to build my own solution files...

cheers

ed

**Comment by polichtm** [comment]
Ed - that's a valid point - we are going away from that approach. Demo instructions will provide only high level guidance, since they are included in the courseware (rather than being kept up-to-date via GitHub)
rgds
Marcin

**Comment by tiagocostapt** [comment]
I agree with @edbakermct on the demos thing. We should have demos that are not the same has the labs (or almost the same), this way we can use 2 learning moments to learn different features. Maybe we can see this on 'E' Version of the course?
