### ISSUE TITLE
Mod 10 nested template schema error

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#310]
When running Add-20533Denvironment on mod 10, the template validation fails with the below error (in graphic) essentially there is a mismatch between the schema versions for the vnet nested template 
![image](https://user-images.githubusercontent.com/23341813/37817619-aed175de-2e77-11e8-8b53-035f27543beb.png)

**Comment by edbakermct** [comment]
Tried using the original old scripts and the same error.

**Comment by edbakermct** [comment]
Concluded it must either be a regional or a tenant error as a colleague ran the same script on a different tenant and region and it still works.

**Comment by polichtm** [comment]
Hi Ed, 
I'm not able to reproduce this issue either. 
Are you using the lab VM? 
rgds
Marcin

**Comment by polichtm** [comment]
closed due to lack of response
