### ISSUE TITLE
Error in module 2 lab

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#312]
In 20533D_LAB_02.md, Lab B, Exercise 3 task 1, pt. 3 AND task 2, pt.1 the Azure VM to connect to should be 20533D0201-vm1

In 20533D_LAB_AK_02.md it's Exercise 3 task 2, pt. 1 and 7. Change VM to 20533D0201-vm1

**Comment by polichtm** [comment]
the intention is to allow ICMPv4 on the VM that functions as the router (20533D0201-vm2) and run the test from the VM on the other vnet (20533D0202-vm1)
rgds
Marcin
