### ISSUE TITLE
Lab 7 typo

### ISSUE THREAD

**Issue by ZeffyReport** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#317]
Lab A; Ex 1; Task 2; point 17
 variables should be as below (extra '\' before '.docker')
•--tlscacert: C:\Users\Student\.docker\machine\certs\ca.pem
•--tlscert: C:\Users\Student\.docker\machine\certs\cert.pem
•--tlskey: C:\Users\Student\.docker\machine\certs\key.pem

**Comment by polichtm** [comment]
Can you clarify what you mean by extra "?
thnx
Marcin

**Comment by ZeffyReport** [comment]
Hi Marcin,

The parameters for point 17 say

--tlscacert: *C:\Users\Student.docker\machine\certs\ca.pem*
-

--tlscert: *C:\Users\Student.docker\machine\certs\cert.pem*
-

--tlskey: *C:\Users\Student.docker\machine\certs\key.pem*
and should say
--tlscacert: *C:\Users\Student\.docker\machine\certs\ca.pem*
-

--tlscert: *C:\Users\Student\.docker\machine\certs\cert.pem*
-

--tlskey: *C:\Users\Student\.docker\machine\certs\key.pem*
Geoff

**Comment by polichtm** [comment]
Hi Geoff,
it's actually there - it's the formatting - corrected
rgds
Marcin
