### ISSUE TITLE
Docker compose not working

### ISSUE THREAD

**Issue by rajaniesh** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#324]
I copied the exact same text file or event the copose info given in this site but it throws me this error. Please
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in ".\docker-compose.yml", line 7, column 11

Also if you use the original file given in the git and copy it this will never work and it will throw many errore

Regards
Rajaniesh

**Comment by polichtm** [comment]
Hi Rajaniesh,
which exercise and which step in that exercise are you referring to?
rgds,
Marcin

**Comment by rajaniesh** [comment]
chapter 7 exercise showing wicker compose

**Comment by rajaniesh** [comment]
any update

**Comment by polichtm** [comment]
I'm not able to reproduce the issue you are running into. Can you post the yml file you are using?
thnx
Marcin

**Comment by rajaniesh** [comment]
just copy the answer yml file given in the solution folder

**Comment by tiagocostapt** [comment]
sometimes some students have some issues doing this step of the lab. Usually is because the yml file is not correct. Try to copy exactly the file and see if it helps.

**Comment by rajaniesh** [comment]
I copied the same file and it did not worked even I added spaces it did not worked if you want I can send u video of it

**Comment by polichtm** [comment]
I just stepped through the lab and did not run any issues. Here is the file I used:
  version: "3"
  services:
    wordpress:
      image: wordpress
      links:
        - db:mysql
      ports:
        - 8080:80
    db:
       image: mariadb
       environment:
         MYSQL_ROOT_PASSWORD: Pa55w.rd

And here is the output of the session:

C:\Users\demouser>docker-machine env 20533d0702-vm0
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://40.117.128.27:2376
SET DOCKER_CERT_PATH=C:\Users\demouser\.docker\machine\machines\20533d0702-vm0
SET DOCKER_MACHINE_NAME=20533d0702-vm0
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env 20533d0702-vm0') DO @%i

C:\Users\demouser>@FOR /f "tokens=*" %i IN ('docker-machine env 20533d0702-vm0') DO @%i

C:\Users\demouser>SET DOCKER
DOCKER_CERT_PATH=C:\Users\demouser\.docker\machine\machines\20533d0702-vm0
DOCKER_HOST=tcp://40.117.128.27:2376
DOCKER_MACHINE_NAME=20533d0702-vm0
DOCKER_TLS_VERIFY=1

C:\Users\demouser>docker run -d -p 80:80 --restart=always nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
f2aa67a397c4: Pull complete
3c091c23e29d: Pull complete
4a99993b8636: Pull complete
Digest: sha256:0fb320e2a1b1620b4905facb3447e3d84ad36da0b2c8aa8fe3a5a81d1187b884
Status: Downloaded newer image for nginx:latest
4be3560da05220cabb894618da5fcf086ad1233f454efeabfdceb0b0d47a1425

C:\Users\demouser>notepad docker-compose.yml

C:\Users\demouser>docker-compose up -d
Creating network "demouser_default" with the default driver
Pulling db (mariadb:)...
latest: Pulling from library/mariadb
3d77ce4481b1: Pull complete
4f6a779d83f5: Pull complete
8c1d272f25d5: Pull complete
672dd5e0b768: Pull complete
84a7291b5996: Pull complete
92edc8e8d33d: Pull complete
f86a82067817: Pull complete
8eff7352c12e: Pull complete
705e5fd937c3: Pull complete
8e85dd313344: Pull complete
7e01ce16c2fa: Pull complete
Digest: sha256:41d776c7e619b5dbbe3391024a508e63887f3915bca6329e7bc0b933b0aa7645
Status: Downloaded newer image for mariadb:latest
Pulling wordpress (wordpress:)...
latest: Pulling from library/wordpress
f2aa67a397c4: Already exists
c533bdb78a46: Pull complete
65a7293804ac: Pull complete
35a9c1f94aea: Pull complete
651774c607cc: Pull complete
7c01fbe5ed3d: Pull complete
9ff29ed84bfc: Pull complete
647feb0f6355: Pull complete
0b9d1c540863: Pull complete
3416ab5471ed: Pull complete
246c5fc29b1a: Pull complete
98923ca5a50a: Pull complete
8931bc5b7082: Pull complete
fb2e6680ec40: Pull complete
36c71eb6672c: Pull complete
aee6d1701877: Pull complete
b48dafdceab4: Pull complete
b8b77748246f: Pull complete
ae3947bf258f: Pull complete
76bf79d20589: Pull complete
Digest: sha256:15e2a017680bf1fadbaa0c9513b95ec2aba42e505ae93a394d766b4bdccc4ab2
Status: Downloaded newer image for wordpress:latest
Creating demouser_db_1 ... done
Creating demouser_wordpress_1 ... done

What specifically is failing for you?

rgds
Marcin

**Comment by polichtm** [comment]
closing due to inability to reproduce the issue and lack of response

**Comment by rajaniesh** [comment]
It started working when I executed the steps provided by you.
But there is a gap in what is provided in the book and what you have provided here
This is what is given in the answer key of @ this link https://www.skillpipe.com/en-GB/Read/71aae62f-e964-40b8-86f0-0fd8040393e0 

version: "3" services: wordpress:
image: wordpress
links:
- db:mysql
ports:
- 8080:80
db:
image: mariadb
environment:
MYSQL_ROOT_PASSWORD: Pa55w.rd

**Comment by polichtm** [comment]
Rajaniesh, 
I'm glad we managed to get this resolved. I also updated the docker-compose.yml in the Solution folder. 
Which book are you referring to?
rgds
Marcin

**Comment by rajaniesh** [comment]
Marcin,

I was referring to **Implementing Microsoft Azure Infrastructure Solutions** OD20533D-NoLab
