### ISSUE TITLE
Lab8 Configure RDP access throws the error

### ISSUE THREAD

**Issue by rajaniesh** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#327]
Hi,

I found another problem in the course:

I ran these commands:

Add-AzureAccount
Get-AzureSubscription
Select-AzureSubscription -SubscriptionId '9eddabc8-5df1-46c7-8b21-69f6d848616d'

$serviceName = 'MyCloudLab'
$userName = 'Student'
$securePassword = 'Pa55w.rd1234' | ConvertTo-SecureString -AsPlainText -Force
$expirationDate = $(Get-Date).AddDays(31)
$credential = New-Object System.Management.Automation.PSCredential $userName,$securePassword
Set-AzureServiceRemoteDesktopExtension -ServiceName $serviceName -Credential $credential -Expiration $expirationDate -Slot Production
Set-AzureServiceRemoteDesktopExtension -ServiceName $serviceName -Credential $credential -Expiration $expirationDate -Slot Staging

But it throws this error

Set-AzureServiceRemoteDesktopExtension : Your Azure credentials have not been set up or have expired, please run 
Add-AzureAccount to set up your Azure credentials.
At line:7 char:1
+ Set-AzureServiceRemoteDesktopExtension -ServiceName $serviceName -Cre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureServiceRemoteDesktopExtension], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.Se 
   tAzureServiceRemoteDesktopExtensionCommand
 
Set-AzureServiceRemoteDesktopExtension : Your Azure credentials have not been set up or have expired, please run 
Add-AzureAccount to set up your Azure credentials.
At line:8 char:1
+ Set-AzureServiceRemoteDesktopExtension -ServiceName $serviceName -Cre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureServiceRemoteDesktopExtension], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.Se 
   tAzureServiceRemoteDesktopExtensionCommand
 

PS C:\WINDOWS\system32> Set-AzureServiceRemoteDesktopExtension -ServiceName $serviceName -Credential $credential 
Set-AzureServiceRemoteDesktopExtension : Your Azure credentials have not been set up or have expired, please run 
Add-AzureAccount to set up your Azure credentials.
At line:1 char:1
+ Set-AzureServiceRemoteDesktopExtension -ServiceName $serviceName -Cre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureServiceRemoteDesktopExtension], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.Se 
   tAzureServiceRemoteDesktopExtensionCommand
 

PS C:\WINDOWS\system32>

**Comment by polichtm** [comment]
Hi Rajaniesh,
Unfortunately I cannot reproduce this issue. 
Have you tried rerunning Add-AzureAccount?
rgds
Marcin

**Comment by polichtm** [comment]
non-reproducible - closed due to lack of response
