### ISSUE TITLE
Adum website throws many errors in Lab 08:Task 3: Test connectivity 

### ISSUE THREAD

**Issue by rajaniesh** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#328]
Hi,

I was testing the outcome of your lab ..It seems that nobody tested the lab . It throws me this error

  <configuration>     <system.web>         <customErrors mode="Off"/>     </system.web> </configuration>
--

**Comment by polichtm** [comment]
Rajaniesh,
This lab has been used multiple times since its release 7 months ago.
What specifically are the errors you are seeing?
rgds
Marcin

**Comment by rajaniesh** [comment]
I resolved the issue but I still feel that instructions are not pretty clear

**Comment by polichtm** [comment]
Rajeniesh,
you really need to be more specific. What exactly is the issue you are referring to and what is the resolution you used?
rgds
Marcin

**Comment by edbakermct** [comment]
Ran all labs this week ZERO errors apart from region specific issues we use Southeast Asia and the av set script needs amending to 2 fault domains

All other labs work

Demos are hampered by subscription policy limits on regions such as default container demo docket machine wants west us but NOVMS were allowed in that region in my azure pass sub

Labs are good thanks for hard work keeping them current

Ed

Sent from iOS Outlook<https://aka.ms/qtex0l> protected by Microsoft Enterprise Mobility and Security
________________________________

**Comment by polichtm** [comment]
Ed – appreciated…

Rgds
Marcin

**Comment by edbakermct** [comment]
one minor comment, could the add environment script text for each module describe exactly what is going to be created. (when more than one vm is required, it asks the vm size maybe 10 minutes intot he script, so students create lab at beginning and go back to it to find it hanging waiting for parameter input of vmsize. for some with dsc this can take a further 25 minutes.

in accelerated courses this can quite seriously hamper some students and the course timings. minor i know but frustrating for them. (if not in the script then a text doc separately in all files with a list of objects / resources created for each lab)

cheers

ed

**Comment by polichtm** [comment]
Hi Ed,
valid point - we'll look into providing all relevant info when the script is launched and streamlining provisioning process
rgds
Marcin

**Comment by polichtm** [comment]
Ed et al.
There are changes to the way the VM size info is handled during provisioning scripts. Rather than having to type the size when prompted (sometimes multiple times), the script prompts once to select a size from a precreated list and this size is used during subsequent template deployment. The list of VM sizes that the script presents is based on the content of Configfiles\VMSizes.txt - so you can customize it any way you prefer before starting the labs.
Hope this helps - any constructive feedback is always welcomed
rgds
Marcin
