### ISSUE TITLE
20533D_LAB_03

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#331]
Exercise 1 - Task 2 - Step 2

In the Windows PowerShell ISE, open the script E:\Labfiles\Lab03\Starter\New-AzureRm20533D03VM.ps1 and review its content.

There is no file called E:\Labfiles\Lab03\Starter\New-AzureRm20533D03VM.ps1

**Comment by renaudwangler** [comment]
The Lab Answer Key is correct : just use the "New-20533D03labVM2.ps1", the only script in the starter folder !

**Comment by polichtm** [comment]
resolved by #331
