### ISSUE TITLE
Lab 2B: Ex 2 Task 3 Step 2: Download RDP file button (new)

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#333]
Lab 2B: Ex 2 Task 3 After Step 2: Add new step because of new Download RDP File button:

"On the Connect to virtual machine blade, click Download RDP File."

![screenshot 1915](https://user-images.githubusercontent.com/22414394/40444274-e23f69b8-5e96-11e8-9ff8-ab4170f1ea4f.png)

This applies to ALL lab steps that connect to a VM through RDP or SSH.

**Comment by polichtm** [comment]
updated this instance - will follow up regarding any others
thnx
Marcin

**Comment by polichtm** [comment]
this has been updated
thnx
Marcin
