### ISSUE TITLE
Lab 09 Get extension error

### ISSUE THREAD

**Issue by alihk79** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#347]
In Exercise 2 Task 2 step 9 after click on Get to install the extension and I should wait till the extension be downloaded, nothing happen and I am sticking on that phase

Regards

**Comment by alihk79** [comment]
it worked on IE11 but not on Edge

Regards,

**Comment by polichtm** [comment]
Can you confirm whether you are using the lab VM?
Can you download other apps from the Store?
rgds
Marcin

**Comment by alihk79** [comment]
I am using the VM on microsoft lab online, on edge i cannot use any app, I tried many , nothing happened when i click on Get
________________________________

**Comment by renaudwangler** [comment]
I totally agree (didn't test it on the new "E" version though) : the Windows Store needs the Windows Update service to be running to accept installing new apps.
I direct my students to test the lab result on the host computer (we use Windows 10).

**Comment by alihk79** [comment]
Yes i did run the update services but still didnt work
________________________________

**Comment by renaudwangler** [comment]
Indeed, When it worked for me I RAN the entire Windows Update.... The Windows Store refused to install new apps before the system was up to date (that's why I use the physical Windows 10 : to avoid updating thnigs in the MIA-CL1 VM that were not supposed to be updated)

**Comment by polichtm** [comment]
changed instructions to use IE
