### ISSUE TITLE
Error in Labfiles\Lab03\Starter\New-20533E03labVM2.ps1 - related to issue #336

### ISSUE THREAD

**Issue by Nailzy** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#348]
Line 57 fails because the input is expecting StandardLRS or PremiumLRS, but the variable being created in Line 21 is putting it as Standard_LRS or Premium_LRS.

PS C:\Users\Student> $osDiskType
Standard_LRS

Set-AzureRmVMOSDisk : Cannot bind parameter 'StorageAccountType'. Cannot convert value
"Standard_LRS" to type "Microsoft.Azure.Management.Compute.Models.StorageAccountTypes". Error:
"Unable to match the identifier name Standard_LRS to a valid enumerator name. Specify one of the
following enumerator names and try again:
StandardLRS, PremiumLRS"
At E:\Labfiles\Lab03\Starter\New-20533E03labVM2.ps1:57 char:99

For a workaround, I've updated line 21 to

$osDiskType = (Get-AzureRmResource -ResourceGroupName $rgName -ResourceType Microsoft.Compute/disks)[0].Sku.name -Replace '_',""

**Comment by polichtm** [comment]
Pls use the current version of the script, which includes the following 
$osDiskType = (Get-AzureRmResource -ResourceGroupName $rgName -ResourceType Microsoft.Compute/disks)[0].Sku.name
thnx
Marcin

**Comment by Nailzy** [comment]
As I said, that doesn't work. The variable returns Standard_LRS (the underscore causes the issue for Set-AzureRmVMOSDisk)

$osDiskType = (Get-AzureRmResource -ResourceGroupName $rgName -ResourceType Microsoft.Compute/disks)[0].Sku.name

Returns Standard_LRS

Then line 57 (Set-AzureRmVMOSDisk) fails because it's expecting StandardLRS or PremiumLRS (without the underscore)

**Comment by Nailzy** [comment]
Tried with both AzureRM 4.4.0 which was on the lab environment, and on AzureRM 6.3.0 .

Deploying to West Europe. Currently doing a QA course and all delegates facing the same issue, not just me.

![image](https://user-images.githubusercontent.com/9915267/41650454-faf9afc8-7475-11e8-8cb3-121b1a0cc17f.png)

![image](https://user-images.githubusercontent.com/9915267/41650500-15033e84-7476-11e8-94ff-b927f2c7c0c5.png)

**Comment by polichtm** [comment]
I tried deploying to West Europe but still cannot reproduce the issue I'm running into. The script has been updated to account for the behavior you are seeing. Let us know if this does not provide a resolution
rgds
Marcin
