### ISSUE TITLE
Error in New-20533D03LabVM2.ps1 in E:\Labfiles\Lab03\Starter - osDiskType return Standard_LRS but azure expect StandardLRS

### ISSUE THREAD

**Issue by spywen** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#354]
Hi, 

We discovered a problem with #336 ticket which is now closed. A fix has been done but unfortunately this fix seems to  work only for some of us.  FYI: We are working on westeurope zone
And when we execute the command:
```
#$osDiskType = (Get-AzureRmResource -ResourceGroupName $rgName -ResourceType Microsoft.Compute/disks)[0].Sku.name
```
We get 'Standard_LRS' but azure anwser is -> 'need StandardLRS'. 

Thanks for your time ;)

**Comment by polichtm** [comment]
The fix applied to #336 involved the following part of New-20533E03labVM2.ps1

try {
    Set-AzureRmVMOSDisk -VM $vmConfig -Name $osDiskName -DiskSizeInGB $osDiskSize -StorageAccountType $osDiskType -CreateOption fromImage
} catch {
    $osDiskType = (Get-AzureRmResource -ResourceGroupName $rgName -ResourceType Microsoft.Compute/disks)[0].Sku.name -Replace '_',""
    Set-AzureRmVMOSDisk -VM $vmConfig -Name $osDiskName -DiskSizeInGB $osDiskSize -StorageAccountType $osDiskType -CreateOption fromImage
}

Can you confirm that you are running the script including this change - and if so, post the error message that you are seeing?
rgds
Marcin

**Comment by spywen** [comment]
Hello thanks for the quick answer.
Let me take the last sources ;) 
Anyway, strange the fix :)

**Comment by polichtm** [comment]
You’re welcome…
