### ISSUE TITLE
How to launch script for Lab02B

### ISSUE THREAD

**Issue by juliogarciacanohotmail** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#357]
Is the Add-20533EEnvironment.psm1 a valid script to generate VMs and resources needed for the lab02B? Where are the instructions to launch it?
It seems to be a Function inside it and not a valid script

Am I wrong?

**Comment by dpapkin** [comment]
It is valid. You just run it from the VM. Type Add-20533 and hit TAB. If it doest auto-fill, then it wont run It is using Powershell modules, which is in the Modules Folder


At the end of the module, run Remove-20533 Environment


DP


________________________________

**Comment by polichtm** [comment]
The instructions to run the module are provided in each module (as part of the initial demo)
"Prepare the lab environment
1.	On the taskbar, right-click Windows PowerShell, and then click Run as administrator. In the User Account Control dialog box, click Yes.
2.	Type the following command, and then press Enter:
Add-20533EEnvironment
3.	At the prompt, type the module number, and then press Enter.
4.	Confirm your selection, and then press Enter. 
This script might affect existing Azure services in your subscription. We recommend that you use an Azure subscription that was provisioned specifically for this course.
The script will configure your lab environment, preparing it for the demonstrations and lab in this module."
rgds
Marcin
