### ISSUE TITLE
AzureRM PS Module problem

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#360]
In Lab 3, Exercice 3, Task 2 point 6, the foloowing command won't work with the AzureRM powershell module provided in the MIA-CL1 VM :
"get-azurermResource -resourcegroupname"
Another command may be used or the command may be used in the Cloud Shell since this is probably due to an outdated version of the PS module.

**Comment by polichtm** [comment]
Hi Renaud,
addressed (replaced with Find-AzureRmResource)
rgds
Marcin
