### ISSUE TITLE
Lab 8 Ex 2 Task 2 Step 11: Create target resources fails

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#362]
Lab 8 Ex 2 Task 2 Step 11: Create target resources fails
![screenshot 2437](https://user-images.githubusercontent.com/22414394/42842382-0f3948fc-89db-11e8-9194-bdbb492f6138.png)

No apparent error to diagnose. Cannot proceed. Any ideas?

**Comment by polichtm** [comment]
Closing due to lack of response
