### ISSUE TITLE
Lab 7B, Ex. 1: Creating an ACS Cluster, Step 8 when running the command kubectl get nodes

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#363]
Hi,

It seems most kubectl commands fail. 

David Papkin

![mod7 fail](https://user-images.githubusercontent.com/24426530/42921197-27979052-8b4d-11e8-80ff-91f92f3a3cc0.PNG)

**Comment by begler1** [comment]
It looks like there is a problem with “kubectl get” in general.  Try “kubectl describe” as a more verbose alternative.

e.g. For “kubectl get nodes”: If you get a response "No resources found", try:
kubectl describe nodes 


Same for “kubectl get pods” and “kubectl get services”. Try:
kubectl describe pods 
kubectl describe services

If you use: 
kubectl describe services 
look for the value of Load Balancer Ingress for the external IP address 

The other “kubectl” commands work ok for me.

Hope this helps.

**Comment by dpapkin** [comment]
Hi, yes, that works for me.

I will close this.

Thank you for your help

David Papkin
http://techresources.info
