### ISSUE TITLE
Dynamic expandig of the $env:PSModulePath

### ISSUE THREAD

**Issue by bone187** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#373]
I would add suggest to add `$env:PSModulePath = $env:PSModulePath + ";$pwd" | Split-Path`
to the Module `Add-20533EEnvironment.psm1` so that the module can be run without adding the path to `$env:PSModulePath`

**Comment by polichtm** [comment]
I might be missing something, but how would you ensure that the you can invoke Add-20533EEnvironment.psm1 in the first place?
rgds
Marcin

**Comment by bone187** [comment]
Hello Marcin,
thank you for the fast reply.
Maybe I miss something. I'm currently taking the course and our trainer missed to give us the lastest course material so I decided to clone the repository to my local machine.
If I run the module without modifying the `$env:PSModulePath` I get errors because the module will not find the function call `Select-20533ESubscriptionARM`:
```
Select-20533ESubscriptionARM : The term 'Select-20533ESubscriptionARM' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Users\Marcel\Development\20533-ImplementingMicrosoftAzureInfrastructureSolutions\Allfiles\Modules\Add-20533EEnvir
onment\Add-20533EEnvironment.psm1:60 char:32
+         1 {Add-AzureRmAccount; Select-20533ESubscriptionARM; Select-2 ...
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Select-20533ESubscriptionARM:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by polichtm** [comment]
Hi Marcel,
you should be using the VM image that is configured specifically for this course. Cloning the repository is not sufficient and is not the intended method of using this course.
The location of modules should be added to the PSModulePath environment variable - this is already implemented in the VM image.
rgds
Marcin
