### ISSUE TITLE
Lab 6, Exercise 3: Protecting Data with Azure Backup | Unable to remove Vault

### ISSUE THREAD

**Issue by gerguk** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#394]
Hi All,

This is very minor but maybe useful.

In step 40 of 'Lab 6, Exercise 3: Protecting Data with Azure Backup' we are advised to perform steps to remove the vault. I was able to delete the server in step 43 but it was not removed. In Step 44 removal of the vault fails.

I had created the vault using Powershell
```
$VaultName = 'vault20533D061'
$ResourceGroupName = '20533D0603-LabRG'
$Location = 'East US'
New-AzureRmRecoveryServicesVault -Name $VaultName -ResourceGroupName $ResourceGroupName -Location $Location
```

Tried to remove it using Powershell
`Get-AzureRmRecoveryServicesVault -ResourceGroupName $ResourceGroupName -Name $VaultName | Remove-AzureRmRecoveryServicesVault`

Ran this to see what was going on
`Get-AzureRmRecoveryServicesVault -ResourceGroupName $ResourceGroupName -Name $VaultName | Remove-AzureRmRecoveryServicesVault -Debug`

Can see this in the output

> Vault cannot be deleted as there are existing resources within the vault. Please ensure there are no backup items, protected servers or backup management servers associated with this vault. Unregister the following containers associated with this vault before proceeding for deletion : MIA-CL1. Unregister all containers from the vault and then retry to delete vault.

I suspect that the vault can't be deleted until the 14 days retention has passed.

As I said it's minor!

Cheers,
Gerg

**Comment by gerguk** [comment]
This might relate to #335

**Comment by polichtm** [comment]
Hello Gerg,
can you advise why you are still using version D of the course?
rgds
Marcin

**Comment by polichtm** [comment]
Hello Gerg,
btw. for the detailed steps describing the procedure to follow, pls refer to https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/blob/master/Instructions/20533E_LAB_AK_08.md 
rgds
Marcin
