### ISSUE TITLE
Module 5 - Task 3 - Deployment Credentials

### ISSUE THREAD

**Issue by rvcondon** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#398]
Task 3: Configure deployment credentials
In the Azure portal, in the web app that you created in the first task, on the web app blade, in the DEPLOYMENT section click Deployment credentials.

Updated Location:
Deployment Blade, Deployment Center - FTP Dashboard - User Credentials

**Comment by polichtm** [comment]
updated
