### ISSUE TITLE
Lab 7 Azure VM Docker extension error (retired?)

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#403]
Error during setup of Lab 7: (see screenshot below)

Doc says:  Warning
The Azure Docker VM extension for Linux is deprecated and will be retired November 2018. The extension merely installs Docker, so alternatives such as cloud-init or the Custom Script Extension are a better way to install the Docker version of choice. For more information on how to use cloud-init, see Customize a Linux VM with cloud-init.

Source: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/dockerextension 
![screenshot 2653](https://user-images.githubusercontent.com/22414394/48211026-9ca3da80-e346-11e8-941b-c7d248e899b6.png)

**Comment by begler1** [comment]
Was able to continue after the above error and to install Docker manually before the first docker command by using:

sudo apt install docker.io 
(and confirming by entering Y for Yes.)

The rest of the lab works as designed.

**Comment by polichtm** [comment]
appreciate the follow up. 
The update is in the works...
rgds
Marcin Policht

**Comment by polichtm** [comment]
resolved
