### ISSUE TITLE
Module 7 setup script

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#404]
I am running the add-20533EEnvironment for module 7, I have tried machine sizes D2_V3 (15) and E2_V3 (16). Both fail with the same error (all students get the same error), which is as follows

New-AzureRmResourceGroupDeployment : 09:34:51 - Resource Microsoft.Compute/virtualMachines/extensions
'20533E0701-vm0/DockerExtension' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'DockerExtension'. Error message: \"Enable
Docker failed: ERROR: executing systemctl [restart docker] failed: exit status 1\"."
      }
    ]
  }
}'
At F:\Modules\Set-20533EEnvironment\Set-20533EEnvironment.psm1:148 char:9
+         New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $Tem ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

**Comment by tonycook2** [comment]
Sorry, I was being stupid. I didn't realise the json template file had been updated

**Comment by polichtm** [comment]
Tony,
np at all...
rgds
Marcin
