### ISSUE TITLE
Module 7, Exercise 1, Task 3, Step 4

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#405]
The class has just been doing the lab for module 7, the lab failed at this command

docker login --username <user name> --password <password> <login-server>

Although the delegates had put in the correct user name, password and login-server they were all getting a permissions error. I mimicked the error by creating my own container registry and tried logging on

docker login --username dockercr1 --password gJf96K/cWJDg23PxhdShTprfzTRPTYFJ dockercr1.azurecr.io

and got the same error

Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.27/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/

After a quick google search, I found an article that suggested I run the following commands

$sudo addgroup --system docker
$sudo adduser $USER docker
$newgrp docker

After running those commands, It logged in successfully. Have you allocated enough permissions in the build scripts?

**Comment by polichtm** [comment]
Hi Tony,
it's a permission-related issue. The instructions are updated to resolve it
rgds
Marcin
