### ISSUE TITLE
Lab 9, Exercise 4 wrong instructions

### ISSUE THREAD

**Issue by RPCMoritz** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#412]
The answer key suggest linking the Karen Gruber account to the **student** account, and when logging into the MIA-CL1 using the student account, SSO as Karen Gruber works, but there's no option on MIA-CL1 to log in as Karen Gruber - the choice of users is predetermined, with no text field available. The mere linking of the accounts, doesn't change this.
Since I don't know what the desired goal is, I can't propose a fix - but I suspect the error is either in preparing the MIA-CL1 correctly, or the login as **student** is sufficient.

**Comment by renaudwangler** [comment]
Hi
I guess you've missed something since the procedure you describe is not the one pointed out in the (current version of) LAK.
Students are directed to "Click Join this device to Azure Active Directory." to make the MIA-CL1 member of the Azure AD and not simply "Connect" the kGruber account with the current local Student account.
After this, they are told to log on using the kGruber account... My understanding is that the goal of this final exercice is to show the real full Azure AD SSO.

(many of my student click on "connect" and miss the "Click Join this device to Azure Active Directory." part)

Hope this helps !

**Comment by RPCMoritz** [comment]
Ah, thanks. It's fairly well hidden, under "alternative actions" - but I didn't find a "non-alternative" entry point for this. I guess I can safely consider this an arcane feature of Azure AD.

**Comment by polichtm** [comment]
Hi Rick,
If you are looking for clarification regarding the purpose of steps in LAK, then you should refer to the corresponding set of instructions (https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/blob/master/Instructions/20533E_LAB_09.md ).
You will find there the following:

"A. Datum has an increasing demand to provide its remote and mobile users, who are using Windows 10-based devices, with secure access to the cloud resources. The company wants to join Windows 10 devices to Azure AD and simplify access to cloud resources by enabling SSO. Before they can implement this, you want to test this functionality by joining a WindowsÂ 10-based computer to Azure AD.
The main tasks for this exercise are as follows:
    Join a Windows 10-based computer to Azure AD
    Authenticate to Azure from a Windows 10 Azure-joined computer
Let us know if this is not clear enough
thnx
Marcin

**Comment by polichtm** [comment]
Hi Rick,
If you are looking for clarification regarding the purpose of steps in LAK, then you should refer to the corresponding set of instructions (https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/blob/master/Instructions/20533E_LAB_09.md ).
You will find there the following:

"A. Datum has an increasing demand to provide its remote and mobile users, who are using Windows 10-based devices, with secure access to the cloud resources. The company wants to join Windows 10 devices to Azure AD and simplify access to cloud resources by enabling SSO. Before they can implement this, you want to test this functionality by joining a WindowsÂ 10-based computer to Azure AD.
The main tasks for this exercise are as follows:
    Join a Windows 10-based computer to Azure AD
    Authenticate to Azure from a Windows 10 Azure-joined computer
Let us know if this is not clear enough
thnx
Marcin
