### ISSUE TITLE
20533E LAB 4 is not working when publishing Dsc configuration

### ISSUE THREAD

**Issue by sichida** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#414]
The following error happens on [this task](https://github.com/MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions/blob/master/Instructions/20533E_LAB_AK_04.md#task-3-install-and-configure-iis-on-azure-vms-by-using-dsc-and-windows-powershell)

```shell
Publish-AzureRmVMDscConfiguration : The remote server returned an error: (403) Forbidden.
At F:\Labfiles\Lab04\Starter\Deploy-20533E0401DSC.ps1:28 char:14
+ ... moduleURL = Publish-AzureRmVMDscConfiguration -ConfigurationPath $con ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureRmVMDscConfiguration], StorageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand
```

The instruction that fails is `Publish-AzureRmVMDscConfiguration -ConfigurationPath $configurationPath -ResourceGroupName $resourceGroupName -StorageAccountName $storageAccount.StorageAccountName -Force`

**Comment by polichtm** [comment]
Hi Shoun,
have you tried the above suggestion?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of the response
