### ISSUE TITLE
20533 Lab 3 LInux deploy exception

### ISSUE THREAD

**Issue by mculver** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#48]
I have no idea what to do with this. Some guidance would be appreciated. In the Visual Studio output from the deployment:

21:39:09 - New-AzureRmResourceGroupDeployment : 9:39:09 PM - Resource Microsoft.Compute/virtualMachines 'ResDevApp1' failed 
21:39:09 - with message '{
21:39:09 -   "error": {
21:39:09 -     "code": "ImageNotFound",
21:39:09 -     "target": "imageReference",
21:39:09 -     "message": "The platform image 'Canonical:UbuntuServer:14.04.2-LTS:latest' is not available. Verify that all 
21:39:09 - fields in the storage profile are correct."
21:39:09 -   }
21:39:09 - }'
21:39:09 - At D:\labfiles\lab03\starter\resdev\resdevlinuxdeploy\resdevlinuxdeploy\Scripts\Deploy-AzureResourceGroup.ps1:98 
21:39:09 - char:1
21:39:09 - + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
21:39:09 - + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:39:09 -     + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
21:39:09 -     + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupD 
21:39:09 -    eploymentCmdlet

**Comment by polichtm** [comment]
As far as I can tell, this is related to the image availability. You can check which Ubuntu images are available by running (replace your_location with the actual location you chose):
foreach ($sku in (Get-AzureRmVMImageSku -Location "Central US" -PublisherName "Canonical" -Offer "UbuntuServer")) {if ((Get-AzureRmVMImage -Location "your_location" -PublisherName "Canonical" -Offer "UbuntuServer" -Skus $sku.Skus -ErrorAction SilentlyContinue).Count -gt 0) {Write-Host $($sku).Skus}}
I'll look into updating instructions accordingly

**Comment by polichtm** [comment]
updated the instructions
