### ISSUE TITLE
20533 Lab 3 ResDevWindowsDeployTemplate.json exception

### ISSUE THREAD

**Issue by mculver** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#49]
Specifying the default value of Standard_D1 size throws an exception, "not available in this region." 

Standard_D1_V2 works.

**Comment by polichtm** [comment]
I'll update instructions to modify the template in case this specific size is not available in the target region

**Comment by polichtm** [comment]
updated
