### ISSUE TITLE
Allow users to join their devices to Azure AD not visible for Azure Passes

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#5]
Did anyone had this experience before?

In Module 9 Lab Exercise 4, users have to verify in their Adatum directory if users are allowed to add their devices to Azure AD.

Task 1: Join a Windows 10-based computer to Azure AD
1. On the taskbar, click Internet Explorer.
2. In Internet Explorer, in the address box, type https://manage.windowsazure.com, and then press Enter. If required, sign in by using the Microsoft account that is associated with your Azure subscription.
3. In the navigation panel on the left, click ACTIVE DIRECTORY.
4. Select the Adatum directory.
5. Click the CONFIGURE tab.
**6. Scroll down to the devices section.
Verify that USERS MAY JOIN DEVICES TO AZURE AD is set to ALL.**

This is not visible. You would expect:
* Directory Properties
* Notifications
* Multifactor authentication
* **Devices
--Users may join devices to Azure AD (all/selected/none)**

However students with an Azure Pass see something different:
* Directory Properties
* Notifications
* Multifactor authentication
* **Group management
* Application Proxy**

This may be different after activating Azure AD Premium.

The exercise still works, students can add their windows 10 device (MIA-CL1) to the Azure AD.

Is this a recent change? My Azure Portal shows the right options.

Marcel

**Comment by polichtm** [comment]
Marcel,

This is correct – this interface is no longer exposed in the Azure classic portal. As you pointed out, the device join still works as expected, since by default, this functionality is enabled. I’ll update instructions accordingly

Rgds

Marcin

**Comment by polichtm** [comment]
Marcel 
I updated the instructions
rgds
Marcin
