### ISSUE TITLE
Lab 4 DeployAzureDSC.ps1 bug

### ISSUE THREAD

**Issue by mculver** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#50]
Line 8 the assignment to $StorageAccountKey returns a null value when specifying .Key1 which in turn causes exceptions to be thrown all over the place.

Should be .Value[0] instead. See https://github.com/Azure/azure-powershell/issues/2212.

**Comment by mculver** [comment]
Also the assignment to $resourceGroupName needs to be "ResDevWebRG not AS. Basic stuff, guys.

**Comment by polichtm** [comment]
The first issue results from you using the newer version of the Azure PowerShell module. Note that you should be using the version of the Azure PowerShell module included in the VM image. If you are using the newer version of the Azure PowerShell module, then you should download the updated version of the script.
I'm not sure what you are referring regarding the second comment. The value of $resourceGroupName is ResDevWebRG in the current version of the script.

**Comment by molenaar** [comment]
What is the reason of this github repository? Keep up with the changes of Azure (the Azure powershell module is now 3.0) or stick with the 1.4 version because of an outdated vmimage?

In my opinion, a C version of the course (with a major update because of an updated Azure) should also be reflected in updated instructions AND scripts. Otherwise we can stay with the b version and use skillpipe.

**Comment by polichtm** [comment]
That is correct - BOTH instructions AND scripts ARE in scope for updates. 
However, Azure the PowerShell module is part of the VM image - and, as such, it is out of scope. This was an intentional design decision. 
If we change this approach, we would need to consider potential backward incompatibility issues with every new release of Azure PowerShell modules (or, if we follow the same logic, with every new release of software component that is part of the build - including Azure SDK, Visual Studio, SQL Server, etc.) - and, on top of that, keep updating the image.

**Comment by mrotrebor** [comment]
Other bug in this file. I tried with the Powershell version of the VM and the last version of the Powershell. It's unacceptable this bugs by Microsoft side in paid courses. 

Publish-AzureRmVMDscConfiguration : The remote server returned an error: (400) Bad Request.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:16 char:14
+ ... moduleURL = Publish-AzureRmVMDscConfiguration -ConfigurationPath $con ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureRmVMDscConfiguration], StorageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand
 
New-AzureStorageContext : Cannot validate argument on parameter 'StorageAccountKey'. The argument is null or empty. Provide an argument that is not null or empty, and then try the 
command again.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:18 char:117
+ ... orageAccount.StorageAccountName -StorageAccountKey $storageAccountKey
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureStorageContext], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext
 
New-AzureStorageContainerSASToken : Could not get the storage context.  Please pass in a storage context or set the current storage context.
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:19 char:13
+ $sasToken = New-AzureStorageContainerSASToken -Name $containerName -C ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureStorageContainerSASToken], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStorageContainerSasTokenCommand
 
Set-AzureRmVMExtension : Long running operation failed with status 'Failed'.
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'DSC'. Error message: "The DSC Extension received an incorrect input: Configuration.function requires that 
configuration.url or configuration.module is specified.
Please correct the input and retry executing the extension.".
StartTime: 28/03/2017 17:39:52
EndTime: 28/03/2017 17:40:55
OperationID: c1704634-eff9-4c05-ab6b-643f09ec5501
Status: Failed
At D:\Labfiles\Lab04\Starter\DeployAzureDSC.ps1:34 char:1
+ Set-AzureRmVMExtension  -ResourceGroupName $resourceGroupName -VMName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand

**Comment by polichtm** [comment]
This has been resolved. Pls give it another try.

**Comment by mrotrebor** [comment]
I tried 6 times, with environment from the beginning. I have tried wit VM, without VM, with VM with your file updated and without VM with your file updated.

Anyway, there are some mistakes in the instructions. For example, if you choose managed disk when you create the Availability Set, and after that, you choose in VM creation "Use managed disks: No", it's not possible to choose the Availability Set created before, it isn't available. 

It's not possible to choose A1 size for VM either.

**Comment by polichtm** [comment]
Hi Roberto,
I just stepped through the lab following the updated instructions and it appears to be working as expected. I assume that the issue you were running into were related to the managed disks settings. This has been updated. If you are still running into an issue, then pls provide the error message.
As far as the availability of A1 goes, we simply suggest the choice of the lowest cost Standard tier VM. You can choose the next level up (I updated instructions accordingly)

**Comment by mrotrebor** [comment]
Finally, it works. I think that the problem was that the Load Balancer hadn't public IP, I don't know why. Thanks for the help @polichtm !
