### ISSUE TITLE
In lab 11 Create-VM.psm1 fails to create RDP file because parent directory does not exist.

### ISSUE THREAD

**Issue by SiloReed** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#67]
In Lab11 this file can't be created by Get-AzureRemoteDesktopFile in line 51 of the Create-VM.psm1 module because the parent directory does not exist:
"D:\Labfiles\Lab11\Starter\AdatumSvr1.rdp"

I inserted these lines at line 12 in order to create the parent directory ($RDPfilesdir) if it doesn't exist:
    if (-not (Test-Path $RDPfilesdir) )
    {
        New-Item -Path $RDPfilesdir -Type directory | Out-Null
    }

**Comment by polichtm** [comment]
Updated
