### ISSUE TITLE
Cant signin to Visual Studio inLab 3

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#68]
We could not add the account [myemail] user_interaction_required : One of two conditions was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame.

![ocaow](https://cloud.githubusercontent.com/assets/13525534/20350028/b16af0a8-ac15-11e6-8913-869921f720cc.png)

**Comment by polichtm** [comment]
try the solution described in http://stackoverflow.com/questions/37818924/microsoft-visual-studio-credential-errors-on-microsoft-azure-account and let us know about the outcome:
Remove the existing account from Visual Studio
2.Close Visual Studio
3.Open a developer command prompt
4.Type devenv.exe /resetuserdata
5.Restart Visual Studio
6.Try and enter you credentials

**Comment by DanePillay-nel** [comment]
Yup tried that. Still doesn't work.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Nov 17, 2016 at 3:03 AM +0200, "polichtm" <notifications@github.com<mailto:notifications@github.com>> wrote:


try the solution described in http://stackoverflow.com/questions/37818924/microsoft-visual-studio-credential-errors-on-microsoft-azure-account and let us know about the outcome:
Remove the existing account from Visual Studio
2.Close Visual Studio
3.Open a developer command prompt
4.Type devenv.exe /resetuserdata
5.Restart Visual Studio
6.Try and enter you credentials

-

**Comment by polichtm** [comment]
Regretfully it's not something I can reproduce. Can you provide access to your system (e.g. via a Skype session) and provide a few dates/times (including your time zone) when you'd be available to troubleshoot this?

**Comment by polichtm** [comment]
Since there was no response, I'm closing this issue
