### ISSUE TITLE
Module 2 Lab B Task 2: Connect to the HQ virtual network #9 Gives certificate error A certificate can not be found that can be used with this Extensible Authentication Protocol

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#77]
Module 2 Lab B Exercise 2: Configuring a point-to-site VPN

Task 2: Connect to the HQ virtual network
1. Switch back to the Internet Explorer tab with the classic portal.
2. On the adatum-hq-vnet page, click DASHBOARD.
3. In the quick glance section, click Download the 64-bit Client VPN Package.
4. When prompted whether to save or run the file, click Run.
5. In the Windows protected your PC dialog box, click More Info, and then click Run anyway.
6. In the User Account Control dialog box, click Yes.
7. In the ADATUM-BRANCH-VNET dialog box, click Yes.
8. In the Search the web and Windows text box, type ncpa.cpl and press Enter.
9. In the Network Connections window, right-click ADATUM-BRANCH-VNET, and then click
Connect/Disconnect. This will launch the Settings app with the VPN tab of NETWORK & INTERNET
page.

At this point there is a popup error msg

![image](https://cloud.githubusercontent.com/assets/24426530/20957014/4b61220e-bc88-11e6-9b57-d776e8335004.png)

**Comment by polichtm** [comment]
Pls provide the screenshot of the Settings->SYSTEM->About window

**Comment by polichtm** [comment]
I cannot reproduce this error - closing issue due to lack of response from dpapkin
