### ISSUE TITLE
When hosting the vm environment directly in Azure, the D: drive is for temporary storage

### ISSUE THREAD

**Issue by jbpaux** [MicrosoftLearning/20533-ImplementingMicrosoftAzureInfrastructureSolutions#82]
I'm delivering the course where the student VM is directly hosted in Azure but the d: drive is used for temporary storage (students have their own msdn license).
It would be nice if the location of the lab files are on another drive (let's say e:) or the location to be configurable in the script or environment variable.

**Comment by polichtm** [comment]
That obviously was not the intended course delivery approach - but we will consider your suggestion going forward. In the meantime, you can use the approach described in https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-windows-classic-change-drive-letter 
rgds
Marcin
